// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class AngiStudieprogrambeskrivelseErrorQueryBuilder : GraphQlQueryBuilder<AngiStudieprogrambeskrivelseErrorQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata = [];

        public AngiStudieprogrambeskrivelseErrorQueryBuilder() => WithTypeName();

        protected override string TypeName => "AngiStudieprogrambeskrivelseError";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public AngiStudieprogrambeskrivelseErrorQueryBuilder WithUgyldigInputFragment(UgyldigInputQueryBuilder ugyldigInputQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(ugyldigInputQueryBuilder, [include, skip]);

        public AngiStudieprogrambeskrivelseErrorQueryBuilder WithStudieprogrambeskrivelseSperretForOppdateringFragment(StudieprogrambeskrivelseSperretForOppdateringQueryBuilder studieprogrambeskrivelseSperretForOppdateringQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(studieprogrambeskrivelseSperretForOppdateringQueryBuilder, [include, skip]);
    }
}
