// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class AngiKriseKontaktpersonForPersonProfilerPayloadQueryBuilder : GraphQlQueryBuilder<AngiKriseKontaktpersonForPersonProfilerPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "kriseKontaktPersoner", IsComplex = true, QueryBuilderType = typeof(KriseKontaktpersonQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(AngiKriseKontaktpersonForPersonProfilerErrorQueryBuilder) }
        };

        protected override string TypeName => "AngiKriseKontaktpersonForPersonProfilerPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public AngiKriseKontaktpersonForPersonProfilerPayloadQueryBuilder WithKriseKontaktPersoner(KriseKontaktpersonQueryBuilder kriseKontaktpersonQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("kriseKontaktPersoner", alias, kriseKontaktpersonQueryBuilder, [include, skip]);

        public AngiKriseKontaktpersonForPersonProfilerPayloadQueryBuilder ExceptKriseKontaktPersoner() => ExceptField("kriseKontaktPersoner");

        public AngiKriseKontaktpersonForPersonProfilerPayloadQueryBuilder WithErrors(AngiKriseKontaktpersonForPersonProfilerErrorQueryBuilder angiKriseKontaktpersonForPersonProfilerErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, angiKriseKontaktpersonForPersonProfilerErrorQueryBuilder, [include, skip]);

        public AngiKriseKontaktpersonForPersonProfilerPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
