// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class AngiLmsKonfigurasjonForUndervisningsenheterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _id;
        private InputPropertyInfo _lmsRomMalId;
        private InputPropertyInfo _skalEksporteresTilLms;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public QueryBuilderParameter<string> Id
        {
            get => (QueryBuilderParameter<string>)_id.Value;
            set => _id = new() { Name = "id", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("lmsRomMalId")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("lmsRomMalId")]
        public QueryBuilderParameter<string> LmsRomMalId
        {
            get => (QueryBuilderParameter<string>)_lmsRomMalId.Value;
            set => _lmsRomMalId = new() { Name = "lmsRomMalId", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("skalEksporteresTilLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("skalEksporteresTilLms")]
        public QueryBuilderParameter<bool?> SkalEksporteresTilLms
        {
            get => (QueryBuilderParameter<bool?>)_skalEksporteresTilLms.Value;
            set => _skalEksporteresTilLms = new() { Name = "skalEksporteresTilLms", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_id.Name != null) yield return _id;
            if (_lmsRomMalId.Name != null) yield return _lmsRomMalId;
            if (_skalEksporteresTilLms.Name != null) yield return _skalEksporteresTilLms;
        }
    }
}
