// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class BegrensProgramStudieretterTilFagErrorQueryBuilder : GraphQlQueryBuilder<BegrensProgramStudieretterTilFagErrorQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata = [];

        public BegrensProgramStudieretterTilFagErrorQueryBuilder() => WithTypeName();

        protected override string TypeName => "BegrensProgramStudieretterTilFagError";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public BegrensProgramStudieretterTilFagErrorQueryBuilder WithUgyldigInputFragment(UgyldigInputQueryBuilder ugyldigInputQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(ugyldigInputQueryBuilder, [include, skip]);
    }
}
