// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class BegrensningForEmnevalgIStudieoppbygningsdelStudienivaQueryBuilder : GraphQlQueryBuilder<BegrensningForEmnevalgIStudieoppbygningsdelStudienivaQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "fraStudieniva", IsComplex = true, QueryBuilderType = typeof(StudienivaQueryBuilder) },
            new() { Name = "tilStudieniva", IsComplex = true, QueryBuilderType = typeof(StudienivaQueryBuilder) }
        };

        protected override string TypeName => "BegrensningForEmnevalgIStudieoppbygningsdelStudieniva";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public BegrensningForEmnevalgIStudieoppbygningsdelStudienivaQueryBuilder WithFraStudieniva(StudienivaQueryBuilder studienivaQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("fraStudieniva", alias, studienivaQueryBuilder, [include, skip]);

        public BegrensningForEmnevalgIStudieoppbygningsdelStudienivaQueryBuilder ExceptFraStudieniva() => ExceptField("fraStudieniva");

        public BegrensningForEmnevalgIStudieoppbygningsdelStudienivaQueryBuilder WithTilStudieniva(StudienivaQueryBuilder studienivaQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("tilStudieniva", alias, studienivaQueryBuilder, [include, skip]);

        public BegrensningForEmnevalgIStudieoppbygningsdelStudienivaQueryBuilder ExceptTilStudieniva() => ExceptField("tilStudieniva");
    }
}
