// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class Betalingsform
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("navnAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("navnAlleSprak")]
        public BetalingsformnavnAlleSprak NavnAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erFelleskode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erFelleskode")]
        public bool? ErFelleskode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erAktiv")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erAktiv")]
        public bool? ErAktiv { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("girSemesterkvittering")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("girSemesterkvittering")]
        public bool? GirSemesterkvittering { get; set; }
    }
}
