// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class BibliotekQueryBuilder : GraphQlQueryBuilder<BibliotekQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "bibliotekkode" },
            new() { Name = "campus", IsComplex = true, QueryBuilderType = typeof(CampusQueryBuilder) },
            new() { Name = "erAktiv" },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(BiblioteknavnAlleSprakQueryBuilder) }
        };

        protected override string TypeName => "Bibliotek";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public BibliotekQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public BibliotekQueryBuilder ExceptId() => ExceptField("id");

        public BibliotekQueryBuilder WithBibliotekkode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("bibliotekkode", alias, [include, skip]);

        public BibliotekQueryBuilder ExceptBibliotekkode() => ExceptField("bibliotekkode");

        public BibliotekQueryBuilder WithCampus(CampusQueryBuilder campusQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("campus", alias, campusQueryBuilder, [include, skip]);

        public BibliotekQueryBuilder ExceptCampus() => ExceptField("campus");

        public BibliotekQueryBuilder WithErAktiv(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erAktiv", alias, [include, skip]);

        public BibliotekQueryBuilder ExceptErAktiv() => ExceptField("erAktiv");

        public BibliotekQueryBuilder WithNavnAlleSprak(BiblioteknavnAlleSprakQueryBuilder biblioteknavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, biblioteknavnAlleSprakQueryBuilder, [include, skip]);

        public BibliotekQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");
    }
}
