// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class CampusBygningerConnectionQueryBuilder : GraphQlQueryBuilder<CampusBygningerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(CampusBygningerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(BygningQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "CampusBygningerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public CampusBygningerConnectionQueryBuilder WithEdges(CampusBygningerConnectionEdgeQueryBuilder campusBygningerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, campusBygningerConnectionEdgeQueryBuilder, [include, skip]);

        public CampusBygningerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public CampusBygningerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public CampusBygningerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public CampusBygningerConnectionQueryBuilder WithNodes(BygningQueryBuilder bygningQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, bygningQueryBuilder, [include, skip]);

        public CampusBygningerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public CampusBygningerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public CampusBygningerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
