// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class DatoperiodeQueryBuilder : GraphQlQueryBuilder<DatoperiodeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "fraDato" },
            new() { Name = "tilDato" }
        };

        public DatoperiodeQueryBuilder() => WithTypeName();

        protected override string TypeName => "Datoperiode";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public DatoperiodeQueryBuilder WithFraDato(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("fraDato", alias, [include, skip]);

        public DatoperiodeQueryBuilder ExceptFraDato() => ExceptField("fraDato");

        public DatoperiodeQueryBuilder WithTilDato(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tilDato", alias, [include, skip]);

        public DatoperiodeQueryBuilder ExceptTilDato() => ExceptField("tilDato");

        public DatoperiodeQueryBuilder WithEmnerolleGyldighetsperiodeFragment(EmnerolleGyldighetsperiodeQueryBuilder emnerolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(emnerolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithKlasserolleGyldighetsperiodeFragment(KlasserolleGyldighetsperiodeQueryBuilder klasserolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(klasserolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithKullrolleGyldighetsperiodeFragment(KullrolleGyldighetsperiodeQueryBuilder kullrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(kullrolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithKursrolleGyldighetsperiodeFragment(KursrolleGyldighetsperiodeQueryBuilder kursrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(kursrolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithOrganisasjonsenhetsrolleGyldighetsperiodeFragment(OrganisasjonsenhetsrolleGyldighetsperiodeQueryBuilder organisasjonsenhetsrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(organisasjonsenhetsrolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithStudieprogramrolleGyldighetsperiodeFragment(StudieprogramrolleGyldighetsperiodeQueryBuilder studieprogramrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(studieprogramrolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithTimeplanrolleGyldighetsperiodeFragment(TimeplanrolleGyldighetsperiodeQueryBuilder timeplanrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(timeplanrolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithUndervisningsaktivitetrolleGyldighetsperiodeFragment(UndervisningsaktivitetrolleGyldighetsperiodeQueryBuilder undervisningsaktivitetrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(undervisningsaktivitetrolleGyldighetsperiodeQueryBuilder, [include, skip]);

        public DatoperiodeQueryBuilder WithUndervisningsenhetsrolleGyldighetsperiodeFragment(UndervisningsenhetsrolleGyldighetsperiodeQueryBuilder undervisningsenhetsrolleGyldighetsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(undervisningsenhetsrolleGyldighetsperiodeQueryBuilder, [include, skip]);
    }
}
