// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("DbhNiva")]
    public partial class DbhNiva : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("dbhNivakode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("dbhNivakode")]
        public string DbhNivakode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("dbhNivanavn")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("dbhNivanavn")]
        public DbhNivanavnAlleSprak DbhNivanavn { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("dbhNivaBeskrivelse")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("dbhNivaBeskrivelse")]
        public DbhNivabeskrivelseAlleSprak DbhNivaBeskrivelse { get; set; }
    }
}
