// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class DeaktiverFagpersonerPayloadQueryBuilder : GraphQlQueryBuilder<DeaktiverFagpersonerPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "fagpersoner", IsComplex = true, QueryBuilderType = typeof(FagpersonVedLarestedQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(DeaktiverFagpersonerErrorsQueryBuilder) }
        };

        protected override string TypeName => "DeaktiverFagpersonerPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public DeaktiverFagpersonerPayloadQueryBuilder WithFagpersoner(FagpersonVedLarestedQueryBuilder fagpersonVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("fagpersoner", alias, fagpersonVedLarestedQueryBuilder, [include, skip]);

        public DeaktiverFagpersonerPayloadQueryBuilder ExceptFagpersoner() => ExceptField("fagpersoner");

        public DeaktiverFagpersonerPayloadQueryBuilder WithErrors(DeaktiverFagpersonerErrorsQueryBuilder deaktiverFagpersonerErrorsQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, deaktiverFagpersonerErrorsQueryBuilder, [include, skip]);

        public DeaktiverFagpersonerPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
