// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class DeaktiverFagpersonerInput : IGraphQlInputObject
    {
        private InputPropertyInfo _id;
        private InputPropertyInfo _fjernInstitusjonsEpost;
        private InputPropertyInfo _fjernFeideBruker;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public QueryBuilderParameter<string> Id
        {
            get => (QueryBuilderParameter<string>)_id.Value;
            set => _id = new() { Name = "id", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fjernInstitusjonsEpost")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fjernInstitusjonsEpost")]
        public QueryBuilderParameter<bool?> FjernInstitusjonsEpost
        {
            get => (QueryBuilderParameter<bool?>)_fjernInstitusjonsEpost.Value;
            set => _fjernInstitusjonsEpost = new() { Name = "fjernInstitusjonsEpost", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fjernFeideBruker")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fjernFeideBruker")]
        public QueryBuilderParameter<bool?> FjernFeideBruker
        {
            get => (QueryBuilderParameter<bool?>)_fjernFeideBruker.Value;
            set => _fjernFeideBruker = new() { Name = "fjernFeideBruker", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_id.Name != null) yield return _id;
            if (_fjernInstitusjonsEpost.Name != null) yield return _fjernInstitusjonsEpost;
            if (_fjernFeideBruker.Name != null) yield return _fjernFeideBruker;
        }
    }
}
