// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Eksamenstilpasningssoknad")]
    public partial class Eksamenstilpasningssoknad : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vurderingsmelding")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vurderingsmelding")]
        public Vurderingsmelding Vurderingsmelding { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("soknadsdato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("soknadsdato")]
        public object Soknadsdato { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("soknadsbeskrivelse")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("soknadsbeskrivelse")]
        public Eksamenstilpasningssoknadsbeskrivelse Soknadsbeskrivelse { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utstyr")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("utstyr")]
        public ICollection<Eksamenstilpasningsutstyr> Utstyr { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("innvilget")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("innvilget")]
        public bool? Innvilget { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("merknad")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("merknad")]
        public Eksamenstilpasningsmerknad Merknad { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("eksamensrom")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("eksamensrom")]
        public Rom Eksamensrom { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("ekstratid")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("ekstratid")]
        public object Ekstratid { get; set; }
    }
}
