// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneSokerTakketJaQueryBuilder : GraphQlQueryBuilder<EmneSokerTakketJaQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "emnesoknad", IsComplex = true, QueryBuilderType = typeof(EmneSoknadQueryBuilder) },
            new() { Name = "student", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedQueryBuilder) },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "EmneSokerTakketJa";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneSokerTakketJaQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EmneSokerTakketJaQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EmneSokerTakketJaQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EmneSokerTakketJaQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EmneSokerTakketJaQueryBuilder WithEmnesoknad(EmneSoknadQueryBuilder emneSoknadQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("emnesoknad", alias, emneSoknadQueryBuilder, [include, skip]);

        public EmneSokerTakketJaQueryBuilder ExceptEmnesoknad() => ExceptField("emnesoknad");

        public EmneSokerTakketJaQueryBuilder WithStudent(StudentVedLarestedQueryBuilder studentVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("student", alias, studentVedLarestedQueryBuilder, [include, skip]);

        public EmneSokerTakketJaQueryBuilder ExceptStudent() => ExceptField("student");

        public EmneSokerTakketJaQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public EmneSokerTakketJaQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");
    }
}
