// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneIStudieoppbygningKullperiodeQueryBuilder : GraphQlQueryBuilder<EmneIStudieoppbygningKullperiodeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "fraKullTermin", IsComplex = true, QueryBuilderType = typeof(TerminQueryBuilder) },
            new() { Name = "tilKullTermin", IsComplex = true, QueryBuilderType = typeof(TerminQueryBuilder) }
        };

        protected override string TypeName => "EmneIStudieoppbygningKullperiode";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneIStudieoppbygningKullperiodeQueryBuilder WithFraKullTermin(TerminQueryBuilder terminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("fraKullTermin", alias, terminQueryBuilder, [include, skip]);

        public EmneIStudieoppbygningKullperiodeQueryBuilder ExceptFraKullTermin() => ExceptField("fraKullTermin");

        public EmneIStudieoppbygningKullperiodeQueryBuilder WithTilKullTermin(TerminQueryBuilder terminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("tilKullTermin", alias, terminQueryBuilder, [include, skip]);

        public EmneIStudieoppbygningKullperiodeQueryBuilder ExceptTilKullTermin() => ExceptField("tilKullTermin");
    }
}
