// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneVurderingsperiodeEndretQueryBuilder : GraphQlQueryBuilder<EmneVurderingsperiodeEndretQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "hendelsestype" },
            new() { Name = "tidspunkt" },
            new() { Name = "emne", IsComplex = true, QueryBuilderType = typeof(EmneQueryBuilder) }
        };

        protected override string TypeName => "EmneVurderingsperiodeEndret";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneVurderingsperiodeEndretQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public EmneVurderingsperiodeEndretQueryBuilder ExceptId() => ExceptField("id");

        public EmneVurderingsperiodeEndretQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EmneVurderingsperiodeEndretQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EmneVurderingsperiodeEndretQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EmneVurderingsperiodeEndretQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EmneVurderingsperiodeEndretQueryBuilder WithEmne(EmneQueryBuilder emneQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("emne", alias, emneQueryBuilder, [include, skip]);

        public EmneVurderingsperiodeEndretQueryBuilder ExceptEmne() => ExceptField("emne");
    }
}
