// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneCampusEndretQueryBuilder : GraphQlQueryBuilder<EmneCampusEndretQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "hendelsestype" },
            new() { Name = "tidspunkt" },
            new() { Name = "emne", IsComplex = true, QueryBuilderType = typeof(EmneQueryBuilder) },
            new() { Name = "campus", IsComplex = true, QueryBuilderType = typeof(EmneCampusQueryBuilder) }
        };

        protected override string TypeName => "EmneCampusEndret";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneCampusEndretQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public EmneCampusEndretQueryBuilder ExceptId() => ExceptField("id");

        public EmneCampusEndretQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EmneCampusEndretQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EmneCampusEndretQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EmneCampusEndretQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EmneCampusEndretQueryBuilder WithEmne(EmneQueryBuilder emneQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("emne", alias, emneQueryBuilder, [include, skip]);

        public EmneCampusEndretQueryBuilder ExceptEmne() => ExceptField("emne");

        public EmneCampusEndretQueryBuilder WithCampus(EmneCampusQueryBuilder emneCampusQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("campus", alias, emneCampusQueryBuilder, [include, skip]);

        public EmneCampusEndretQueryBuilder ExceptCampus() => ExceptField("campus");
    }
}
