// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("EmneStudierett")]
    public partial class EmneStudierett : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emne")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emne")]
        public Emne Emne { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("termin")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("termin")]
        public Termin Termin { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminnummer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminnummer")]
        public int? Terminnummer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("campus")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("campus")]
        public Campus Campus { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningstilpasning")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningstilpasning")]
        public ICollection<Undervisningstilpasning> Undervisningstilpasning { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("student")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("student")]
        public StudentVedLarested Student { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("resultater")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("resultater")]
        public EmneStudierettResultaterConnection Resultater { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("opptakKanPubliseres")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("opptakKanPubliseres")]
        public bool? OpptakKanPubliseres { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningspartiPlasseringer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningspartiPlasseringer")]
        public ICollection<Undervisningspartiplassering> UndervisningspartiPlasseringer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fellesundervisning")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fellesundervisning")]
        public EmneStudierettFellesundervisningConnection Fellesundervisning { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsaktivitetsonsker")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsaktivitetsonsker")]
        public EmneStudierettUndervisningsaktivitetsonskerConnection Undervisningsaktivitetsonsker { get; set; }
    }
}
