// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneAnsvarligeOrganisasjonsenheterQueryBuilder : GraphQlQueryBuilder<EmneAnsvarligeOrganisasjonsenheterQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "studieAnsvarlig", IsComplex = true, QueryBuilderType = typeof(OrganisasjonsenhetQueryBuilder) }
        };

        protected override string TypeName => "EmneAnsvarligeOrganisasjonsenheter";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneAnsvarligeOrganisasjonsenheterQueryBuilder WithStudieAnsvarlig(OrganisasjonsenhetQueryBuilder organisasjonsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("studieAnsvarlig", alias, organisasjonsenhetQueryBuilder, [include, skip]);

        public EmneAnsvarligeOrganisasjonsenheterQueryBuilder ExceptStudieAnsvarlig() => ExceptField("studieAnsvarlig");
    }
}
