// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmnePersonrollerFilter : IGraphQlInputObject
    {
        private InputPropertyInfo _erAktiv;
        private InputPropertyInfo _rollekoder;
        private InputPropertyInfo _kanPubliseres;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erAktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<bool>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erAktiv")]
        public QueryBuilderParameter<ICollection<bool>> ErAktiv
        {
            get => (QueryBuilderParameter<ICollection<bool>>)_erAktiv.Value;
            set => _erAktiv = new() { Name = "erAktiv", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("rollekoder")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("rollekoder")]
        public QueryBuilderParameter<ICollection<string>> Rollekoder
        {
            get => (QueryBuilderParameter<ICollection<string>>)_rollekoder.Value;
            set => _rollekoder = new() { Name = "rollekoder", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kanPubliseres")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kanPubliseres")]
        public QueryBuilderParameter<bool?> KanPubliseres
        {
            get => (QueryBuilderParameter<bool?>)_kanPubliseres.Value;
            set => _kanPubliseres = new() { Name = "kanPubliseres", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_erAktiv.Name != null) yield return _erAktiv;
            if (_rollekoder.Name != null) yield return _rollekoder;
            if (_kanPubliseres.Name != null) yield return _kanPubliseres;
        }
    }
}
