// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneUndervisningsenheterConnectionEdgeQueryBuilder : GraphQlQueryBuilder<EmneUndervisningsenheterConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(UndervisningsenhetQueryBuilder) }
        };

        protected override string TypeName => "EmneUndervisningsenheterConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneUndervisningsenheterConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public EmneUndervisningsenheterConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public EmneUndervisningsenheterConnectionEdgeQueryBuilder WithNode(UndervisningsenhetQueryBuilder undervisningsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, undervisningsenhetQueryBuilder, [include, skip]);

        public EmneUndervisningsenheterConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
