// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmnerollehendelseQueryBuilder : GraphQlQueryBuilder<EmnerollehendelseQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        public EmnerollehendelseQueryBuilder() => WithTypeName();

        protected override string TypeName => "Emnerollehendelse";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmnerollehendelseQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EmnerollehendelseQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EmnerollehendelseQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EmnerollehendelseQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EmnerollehendelseQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public EmnerollehendelseQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");

        public EmnerollehendelseQueryBuilder WithEmnerolleBleAktivFragment(EmnerolleBleAktivQueryBuilder emnerolleBleAktivQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(emnerolleBleAktivQueryBuilder, [include, skip]);

        public EmnerollehendelseQueryBuilder WithEmnerolleBleInaktivFragment(EmnerolleBleInaktivQueryBuilder emnerolleBleInaktivQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(emnerolleBleInaktivQueryBuilder, [include, skip]);

        public EmnerollehendelseQueryBuilder WithEmnerolleEndretFsRolleFragment(EmnerolleEndretFsRolleQueryBuilder emnerolleEndretFsRolleQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(emnerolleEndretFsRolleQueryBuilder, [include, skip]);

        public EmnerollehendelseQueryBuilder WithEmnerolleSlettetFragment(EmnerolleSlettetQueryBuilder emnerolleSlettetQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(emnerolleSlettetQueryBuilder, [include, skip]);
    }
}
