// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EmneIUtdanningsplanResultaterConnectionQueryBuilder : GraphQlQueryBuilder<EmneIUtdanningsplanResultaterConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(EmneIUtdanningsplanResultaterConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(ResultatQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "EmneIUtdanningsplanResultaterConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder WithEdges(EmneIUtdanningsplanResultaterConnectionEdgeQueryBuilder emneIUtdanningsplanResultaterConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, emneIUtdanningsplanResultaterConnectionEdgeQueryBuilder, [include, skip]);

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder WithNodes(ResultatQueryBuilder resultatQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, resultatQueryBuilder, [include, skip]);

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public EmneIUtdanningsplanResultaterConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
