// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EndrePostadresseForStudenterPayload
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studenter")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studenter")]
        public ICollection<StudentVedLarested> Studenter { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("errors")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("errors")]
        public ICollection<UgyldigInput> Errors { get; set; }
    }
}
