// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EndreKullForProgramStudieretterPayloadQueryBuilder : GraphQlQueryBuilder<EndreKullForProgramStudieretterPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "programStudieretter", IsComplex = true, QueryBuilderType = typeof(ProgramStudierettQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(EndreKullForProgramStudieretterErrorQueryBuilder) }
        };

        protected override string TypeName => "EndreKullForProgramStudieretterPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EndreKullForProgramStudieretterPayloadQueryBuilder WithProgramStudieretter(ProgramStudierettQueryBuilder programStudierettQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("programStudieretter", alias, programStudierettQueryBuilder, [include, skip]);

        public EndreKullForProgramStudieretterPayloadQueryBuilder ExceptProgramStudieretter() => ExceptField("programStudieretter");

        public EndreKullForProgramStudieretterPayloadQueryBuilder WithErrors(EndreKullForProgramStudieretterErrorQueryBuilder endreKullForProgramStudieretterErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, endreKullForProgramStudieretterErrorQueryBuilder, [include, skip]);

        public EndreKullForProgramStudieretterPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
