// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EndreLanetakerIdForStudenterPayloadQueryBuilder : GraphQlQueryBuilder<EndreLanetakerIdForStudenterPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "studenter", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedQueryBuilder) }
        };

        protected override string TypeName => "EndreLanetakerIdForStudenterPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EndreLanetakerIdForStudenterPayloadQueryBuilder WithStudenter(StudentVedLarestedQueryBuilder studentVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("studenter", alias, studentVedLarestedQueryBuilder, [include, skip]);

        public EndreLanetakerIdForStudenterPayloadQueryBuilder ExceptStudenter() => ExceptField("studenter");
    }
}
