// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EvuKursSoknadshendelseQueryBuilder : GraphQlQueryBuilder<EvuKursSoknadshendelseQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        public EvuKursSoknadshendelseQueryBuilder() => WithTypeName();

        protected override string TypeName => "EvuKursSoknadshendelse";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EvuKursSoknadshendelseQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EvuKursSoknadshendelseQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EvuKursSoknadshendelseQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSokerIkkeMottFragment(EvuKursSokerIkkeMottQueryBuilder evuKursSokerIkkeMottQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSokerIkkeMottQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSokerMottFragment(EvuKursSokerMottQueryBuilder evuKursSokerMottQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSokerMottQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSokerTakketJaFragment(EvuKursSokerTakketJaQueryBuilder evuKursSokerTakketJaQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSokerTakketJaQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSokerTakketNeiFragment(EvuKursSokerTakketNeiQueryBuilder evuKursSokerTakketNeiQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSokerTakketNeiQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadGittTilbudOmVentelisteplassFragment(EvuKursSoknadGittTilbudOmVentelisteplassQueryBuilder evuKursSoknadGittTilbudOmVentelisteplassQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadGittTilbudOmVentelisteplassQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadInnvilgetFragment(EvuKursSoknadInnvilgetQueryBuilder evuKursSoknadInnvilgetQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadInnvilgetQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadRegistrertFragment(EvuKursSoknadRegistrertQueryBuilder evuKursSoknadRegistrertQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadRegistrertQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadSattPaVentelisteFragment(EvuKursSoknadSattPaVentelisteQueryBuilder evuKursSoknadSattPaVentelisteQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadSattPaVentelisteQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadSlettetFragment(EvuKursSoknadSlettetQueryBuilder evuKursSoknadSlettetQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadSlettetQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadTilbudSendtFragment(EvuKursSoknadTilbudSendtQueryBuilder evuKursSoknadTilbudSendtQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadTilbudSendtQueryBuilder, [include, skip]);

        public EvuKursSoknadshendelseQueryBuilder WithEvuKursSoknadTrukketFragment(EvuKursSoknadTrukketQueryBuilder evuKursSoknadTrukketQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(evuKursSoknadTrukketQueryBuilder, [include, skip]);
    }
}
