// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EvuKursaktivitetQueryBuilder : GraphQlQueryBuilder<EvuKursaktivitetQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kode" },
            new() { Name = "parent", IsComplex = true, QueryBuilderType = typeof(EvuKursaktivitetQueryBuilder) },
            new() { Name = "evuKurs", IsComplex = true, QueryBuilderType = typeof(EvuKursQueryBuilder) },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(EvuKursaktivitetsnavnAlleSprakQueryBuilder) },
            new() { Name = "lmsRomkode" },
            new() { Name = "sekvensnummer" },
            new() { Name = "innledningskommentarAlleSprak", IsComplex = true, QueryBuilderType = typeof(EvuKursaktivitetInnledningskommentarAlleSprakQueryBuilder) }
        };

        protected override string TypeName => "EvuKursaktivitet";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EvuKursaktivitetQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptId() => ExceptField("id");

        public EvuKursaktivitetQueryBuilder WithKode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kode", alias, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptKode() => ExceptField("kode");

        public EvuKursaktivitetQueryBuilder WithParent(EvuKursaktivitetQueryBuilder evuKursaktivitetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("parent", alias, evuKursaktivitetQueryBuilder, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptParent() => ExceptField("parent");

        public EvuKursaktivitetQueryBuilder WithEvuKurs(EvuKursQueryBuilder evuKursQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("evuKurs", alias, evuKursQueryBuilder, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptEvuKurs() => ExceptField("evuKurs");

        public EvuKursaktivitetQueryBuilder WithNavnAlleSprak(EvuKursaktivitetsnavnAlleSprakQueryBuilder evuKursaktivitetsnavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, evuKursaktivitetsnavnAlleSprakQueryBuilder, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");

        public EvuKursaktivitetQueryBuilder WithLmsRomkode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("lmsRomkode", alias, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptLmsRomkode() => ExceptField("lmsRomkode");

        public EvuKursaktivitetQueryBuilder WithSekvensnummer(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("sekvensnummer", alias, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptSekvensnummer() => ExceptField("sekvensnummer");

        public EvuKursaktivitetQueryBuilder WithInnledningskommentarAlleSprak(EvuKursaktivitetInnledningskommentarAlleSprakQueryBuilder evuKursaktivitetInnledningskommentarAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("innledningskommentarAlleSprak", alias, evuKursaktivitetInnledningskommentarAlleSprakQueryBuilder, [include, skip]);

        public EvuKursaktivitetQueryBuilder ExceptInnledningskommentarAlleSprak() => ExceptField("innledningskommentarAlleSprak");
    }
}
