// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EvuKursrolleBleInaktivQueryBuilder : GraphQlQueryBuilder<EvuKursrolleBleInaktivQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "evuKursrolle", IsComplex = true, QueryBuilderType = typeof(EvuKursrolleQueryBuilder) },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "EvuKursrolleBleInaktiv";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EvuKursrolleBleInaktivQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EvuKursrolleBleInaktivQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EvuKursrolleBleInaktivQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EvuKursrolleBleInaktivQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EvuKursrolleBleInaktivQueryBuilder WithEvuKursrolle(EvuKursrolleQueryBuilder evuKursrolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("evuKursrolle", alias, evuKursrolleQueryBuilder, [include, skip]);

        public EvuKursrolleBleInaktivQueryBuilder ExceptEvuKursrolle() => ExceptField("evuKursrolle");

        public EvuKursrolleBleInaktivQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public EvuKursrolleBleInaktivQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");
    }
}
