// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class EvuKursSoknadTrukketQueryBuilder : GraphQlQueryBuilder<EvuKursSoknadTrukketQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "evuKursSoknad", IsComplex = true, QueryBuilderType = typeof(EvuKursSoknadQueryBuilder) },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "EvuKursSoknadTrukket";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public EvuKursSoknadTrukketQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public EvuKursSoknadTrukketQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public EvuKursSoknadTrukketQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public EvuKursSoknadTrukketQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public EvuKursSoknadTrukketQueryBuilder WithEvuKursSoknad(EvuKursSoknadQueryBuilder evuKursSoknadQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("evuKursSoknad", alias, evuKursSoknadQueryBuilder, [include, skip]);

        public EvuKursSoknadTrukketQueryBuilder ExceptEvuKursSoknad() => ExceptField("evuKursSoknad");

        public EvuKursSoknadTrukketQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public EvuKursSoknadTrukketQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");
    }
}
