// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class FagpersonerFilterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _eierOrganisasjonskode;
        private InputPropertyInfo _aktiv;
        private InputPropertyInfo _permisjon;
        private InputPropertyInfo _campus;
        private InputPropertyInfo _inkluderAvdode;
        private InputPropertyInfo _fodselsnumre;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("eierOrganisasjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("eierOrganisasjonskode")]
        public QueryBuilderParameter<string> EierOrganisasjonskode
        {
            get => (QueryBuilderParameter<string>)_eierOrganisasjonskode.Value;
            set => _eierOrganisasjonskode = new() { Name = "eierOrganisasjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("aktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<bool>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("aktiv")]
        public QueryBuilderParameter<ICollection<bool>> Aktiv
        {
            get => (QueryBuilderParameter<ICollection<bool>>)_aktiv.Value;
            set => _aktiv = new() { Name = "aktiv", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("permisjon")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<bool>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("permisjon")]
        public QueryBuilderParameter<ICollection<bool>> Permisjon
        {
            get => (QueryBuilderParameter<ICollection<bool>>)_permisjon.Value;
            set => _permisjon = new() { Name = "permisjon", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("campus")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("campus")]
        public QueryBuilderParameter<ICollection<string>> Campus
        {
            get => (QueryBuilderParameter<ICollection<string>>)_campus.Value;
            set => _campus = new() { Name = "campus", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("inkluderAvdode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("inkluderAvdode")]
        public QueryBuilderParameter<bool?> InkluderAvdode
        {
            get => (QueryBuilderParameter<bool?>)_inkluderAvdode.Value;
            set => _inkluderAvdode = new() { Name = "inkluderAvdode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fodselsnumre")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fodselsnumre")]
        public QueryBuilderParameter<ICollection<string>> Fodselsnumre
        {
            get => (QueryBuilderParameter<ICollection<string>>)_fodselsnumre.Value;
            set => _fodselsnumre = new() { Name = "fodselsnumre", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_eierOrganisasjonskode.Name != null) yield return _eierOrganisasjonskode;
            if (_aktiv.Name != null) yield return _aktiv;
            if (_permisjon.Name != null) yield return _permisjon;
            if (_campus.Name != null) yield return _campus;
            if (_inkluderAvdode.Name != null) yield return _inkluderAvdode;
            if (_fodselsnumre.Name != null) yield return _fodselsnumre;
        }
    }
}
