// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Faktura")]
    public partial class Faktura : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fakturadato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fakturadato")]
        public object Fakturadato { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("termin")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("termin")]
        public Termin Termin { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("betalingsfrist")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("betalingsfrist")]
        public object Betalingsfrist { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fakturareferanse")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fakturareferanse")]
        public string Fakturareferanse { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("detaljer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("detaljer")]
        public ICollection<Fakturadetalj> Detaljer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("belop")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("belop")]
        public object Belop { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kidNummer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kidNummer")]
        public string KidNummer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("betalt")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("betalt")]
        public bool? Betalt { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("innbetaltBelop")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("innbetaltBelop")]
        public object InnbetaltBelop { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("refundertBelop")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("refundertBelop")]
        public object RefundertBelop { get; set; }
    }
}
