// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class FsDokumentQueryBuilder : GraphQlQueryBuilder<FsDokumentQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "filnavn" },
            new() { Name = "filtype" }
        };

        protected override string TypeName => "FsDokument";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public FsDokumentQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public FsDokumentQueryBuilder ExceptId() => ExceptField("id");

        public FsDokumentQueryBuilder WithFilnavn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("filnavn", alias, [include, skip]);

        public FsDokumentQueryBuilder ExceptFilnavn() => ExceptField("filnavn");

        public FsDokumentQueryBuilder WithFiltype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("filtype", alias, [include, skip]);

        public FsDokumentQueryBuilder ExceptFiltype() => ExceptField("filtype");
    }
}
