// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class FsOpptakQueryBuilder : GraphQlQueryBuilder<FsOpptakQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "opptakstype", IsComplex = true, QueryBuilderType = typeof(FsOpptakstypeQueryBuilder) },
            new() { Name = "termin", IsComplex = true, QueryBuilderType = typeof(TerminQueryBuilder) },
            new() { Name = "gjelderUhgOpptak" },
            new() { Name = "soknadsfrist" }
        };

        protected override string TypeName => "FsOpptak";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public FsOpptakQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public FsOpptakQueryBuilder ExceptId() => ExceptField("id");

        public FsOpptakQueryBuilder WithOpptakstype(FsOpptakstypeQueryBuilder fsOpptakstypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("opptakstype", alias, fsOpptakstypeQueryBuilder, [include, skip]);

        public FsOpptakQueryBuilder ExceptOpptakstype() => ExceptField("opptakstype");

        public FsOpptakQueryBuilder WithTermin(TerminQueryBuilder terminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("termin", alias, terminQueryBuilder, [include, skip]);

        public FsOpptakQueryBuilder ExceptTermin() => ExceptField("termin");

        public FsOpptakQueryBuilder WithGjelderUhgOpptak(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("gjelderUhgOpptak", alias, [include, skip]);

        public FsOpptakQueryBuilder ExceptGjelderUhgOpptak() => ExceptField("gjelderUhgOpptak");

        public FsOpptakQueryBuilder WithSoknadsfrist(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("soknadsfrist", alias, [include, skip]);

        public FsOpptakQueryBuilder ExceptSoknadsfrist() => ExceptField("soknadsfrist");
    }
}
