// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class FsSoknadsalternativValgConnectionQueryBuilder : GraphQlQueryBuilder<FsSoknadsalternativValgConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(FsSoknadsalternativValgConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(FsSoknadsvalgQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "FsSoknadsalternativValgConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public FsSoknadsalternativValgConnectionQueryBuilder WithEdges(FsSoknadsalternativValgConnectionEdgeQueryBuilder fsSoknadsalternativValgConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, fsSoknadsalternativValgConnectionEdgeQueryBuilder, [include, skip]);

        public FsSoknadsalternativValgConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public FsSoknadsalternativValgConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public FsSoknadsalternativValgConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public FsSoknadsalternativValgConnectionQueryBuilder WithNodes(FsSoknadsvalgQueryBuilder fsSoknadsvalgQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, fsSoknadsvalgQueryBuilder, [include, skip]);

        public FsSoknadsalternativValgConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public FsSoknadsalternativValgConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public FsSoknadsalternativValgConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
