// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("GodkjentPolitiattest")]
    public partial class GodkjentPolitiattest : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogram")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogram")]
        public Studieprogram Studieprogram { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("politiattest")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("politiattest")]
        public Politiattesttype Politiattest { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fraDato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fraDato")]
        public object FraDato { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tilDato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tilDato")]
        public object TilDato { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("merknad")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("merknad")]
        public GodkjentPolitiattestMerknad Merknad { get; set; }
    }
}
