// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class IndividuellEmnevektingQueryBuilder : GraphQlQueryBuilder<IndividuellEmnevektingQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "verdi" },
            new() { Name = "vektingstype", IsComplex = true, QueryBuilderType = typeof(VektingstypeQueryBuilder) }
        };

        protected override string TypeName => "IndividuellEmnevekting";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public IndividuellEmnevektingQueryBuilder WithVerdi(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("verdi", alias, [include, skip]);

        public IndividuellEmnevektingQueryBuilder ExceptVerdi() => ExceptField("verdi");

        public IndividuellEmnevektingQueryBuilder WithVektingstype(VektingstypeQueryBuilder vektingstypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("vektingstype", alias, vektingstypeQueryBuilder, [include, skip]);

        public IndividuellEmnevektingQueryBuilder ExceptVektingstype() => ExceptField("vektingstype");
    }
}
