// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class InstrumentQueryBuilder : GraphQlQueryBuilder<InstrumentQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "navn", IsComplex = true, QueryBuilderType = typeof(InstrumentnavnQueryBuilder) },
            new() { Name = "instrumentgruppe", IsComplex = true, QueryBuilderType = typeof(InstrumentgruppeQueryBuilder) }
        };

        protected override string TypeName => "Instrument";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public InstrumentQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public InstrumentQueryBuilder ExceptId() => ExceptField("id");

        public InstrumentQueryBuilder WithNavn(InstrumentnavnQueryBuilder instrumentnavnQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navn", alias, instrumentnavnQueryBuilder, [include, skip]);

        public InstrumentQueryBuilder ExceptNavn() => ExceptField("navn");

        public InstrumentQueryBuilder WithInstrumentgruppe(InstrumentgruppeQueryBuilder instrumentgruppeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("instrumentgruppe", alias, instrumentgruppeQueryBuilder, [include, skip]);

        public InstrumentQueryBuilder ExceptInstrumentgruppe() => ExceptField("instrumentgruppe");
    }
}
