// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Institusjonstype")]
    public partial class Institusjonstype : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kode")]
        public string Kode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("beskrivelseAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("beskrivelseAlleSprak")]
        public InstitusjonstypeBeskrivelseAlleSprak BeskrivelseAlleSprak { get; set; }
    }
}
