// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public enum Klasserollehendelsestype
    {
        [EnumMember(Value = "KLASSEROLLE_ENDRET_FSROLLE")] KlasserolleEndretFsrolle,
        [EnumMember(Value = "KLASSEROLLE_BLE_AKTIV")] KlasserolleBleAktiv,
        [EnumMember(Value = "KLASSEROLLE_BLE_INAKTIV")] KlasserolleBleInaktiv,
        [EnumMember(Value = "KLASSEROLLE_SLETTET")] KlasserolleSlettet
    }
}
