// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class KlassemedlemskapAktivertQueryBuilder : GraphQlQueryBuilder<KlassemedlemskapAktivertQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "student", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedQueryBuilder) },
            new() { Name = "klassemedlemskap", IsComplex = true, QueryBuilderType = typeof(KlassemedlemskapQueryBuilder) },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "KlassemedlemskapAktivert";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public KlassemedlemskapAktivertQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public KlassemedlemskapAktivertQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public KlassemedlemskapAktivertQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public KlassemedlemskapAktivertQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public KlassemedlemskapAktivertQueryBuilder WithStudent(StudentVedLarestedQueryBuilder studentVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("student", alias, studentVedLarestedQueryBuilder, [include, skip]);

        public KlassemedlemskapAktivertQueryBuilder ExceptStudent() => ExceptField("student");

        public KlassemedlemskapAktivertQueryBuilder WithKlassemedlemskap(KlassemedlemskapQueryBuilder klassemedlemskapQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("klassemedlemskap", alias, klassemedlemskapQueryBuilder, [include, skip]);

        public KlassemedlemskapAktivertQueryBuilder ExceptKlassemedlemskap() => ExceptField("klassemedlemskap");

        public KlassemedlemskapAktivertQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public KlassemedlemskapAktivertQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");
    }
}
