// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class KommisjonQueryBuilder : GraphQlQueryBuilder<KommisjonQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kommisjonsnummer" },
            new() { Name = "kommisjonsnavn" },
            new() { Name = "sensoroppdrag", IsComplex = true, QueryBuilderType = typeof(SensoroppdragQueryBuilder) }
        };

        protected override string TypeName => "Kommisjon";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public KommisjonQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public KommisjonQueryBuilder ExceptId() => ExceptField("id");

        public KommisjonQueryBuilder WithKommisjonsnummer(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kommisjonsnummer", alias, [include, skip]);

        public KommisjonQueryBuilder ExceptKommisjonsnummer() => ExceptField("kommisjonsnummer");

        public KommisjonQueryBuilder WithKommisjonsnavn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kommisjonsnavn", alias, [include, skip]);

        public KommisjonQueryBuilder ExceptKommisjonsnavn() => ExceptField("kommisjonsnavn");

        public KommisjonQueryBuilder WithSensoroppdrag(SensoroppdragQueryBuilder sensoroppdragQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("sensoroppdrag", alias, sensoroppdragQueryBuilder, [include, skip]);

        public KommisjonQueryBuilder ExceptSensoroppdrag() => ExceptField("sensoroppdrag");
    }
}
