// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class KravelementQueryBuilder : GraphQlQueryBuilder<KravelementQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kode" },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(KravelementnavnAlleSprakQueryBuilder) }
        };

        protected override string TypeName => "Kravelement";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public KravelementQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public KravelementQueryBuilder ExceptId() => ExceptField("id");

        public KravelementQueryBuilder WithKode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kode", alias, [include, skip]);

        public KravelementQueryBuilder ExceptKode() => ExceptField("kode");

        public KravelementQueryBuilder WithNavnAlleSprak(KravelementnavnAlleSprakQueryBuilder kravelementnavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, kravelementnavnAlleSprakQueryBuilder, [include, skip]);

        public KravelementQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");
    }
}
