// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class KullSkalDeaktiveresQueryBuilder : GraphQlQueryBuilder<KullSkalDeaktiveresQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "hendelsestype" },
            new() { Name = "tidspunkt" },
            new() { Name = "studieprogram", IsComplex = true, QueryBuilderType = typeof(StudieprogramQueryBuilder) },
            new() { Name = "kull", IsComplex = true, QueryBuilderType = typeof(KullQueryBuilder) }
        };

        protected override string TypeName => "KullSkalDeaktiveres";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public KullSkalDeaktiveresQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public KullSkalDeaktiveresQueryBuilder ExceptId() => ExceptField("id");

        public KullSkalDeaktiveresQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public KullSkalDeaktiveresQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public KullSkalDeaktiveresQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public KullSkalDeaktiveresQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public KullSkalDeaktiveresQueryBuilder WithStudieprogram(StudieprogramQueryBuilder studieprogramQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("studieprogram", alias, studieprogramQueryBuilder, [include, skip]);

        public KullSkalDeaktiveresQueryBuilder ExceptStudieprogram() => ExceptField("studieprogram");

        public KullSkalDeaktiveresQueryBuilder WithKull(KullQueryBuilder kullQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("kull", alias, kullQueryBuilder, [include, skip]);

        public KullSkalDeaktiveresQueryBuilder ExceptKull() => ExceptField("kull");
    }
}
