// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class KursavbruddarsaknavnAlleSprakQueryBuilder : GraphQlQueryBuilder<KursavbruddarsaknavnAlleSprakQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "nb" },
            new() { Name = "nn" },
            new() { Name = "en" }
        };

        protected override string TypeName => "KursavbruddarsaknavnAlleSprak";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public KursavbruddarsaknavnAlleSprakQueryBuilder WithNb(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("nb", alias, [include, skip]);

        public KursavbruddarsaknavnAlleSprakQueryBuilder ExceptNb() => ExceptField("nb");

        public KursavbruddarsaknavnAlleSprakQueryBuilder WithNn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("nn", alias, [include, skip]);

        public KursavbruddarsaknavnAlleSprakQueryBuilder ExceptNn() => ExceptField("nn");

        public KursavbruddarsaknavnAlleSprakQueryBuilder WithEn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("en", alias, [include, skip]);

        public KursavbruddarsaknavnAlleSprakQueryBuilder ExceptEn() => ExceptField("en");
    }
}
