// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Land")]
    public partial class Land : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("landkodeAlfa3")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("landkodeAlfa3")]
        public string LandkodeAlfa3 { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("navnAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("navnAlleSprak")]
        public LandnavnAlleSprak NavnAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("landkodeAlfa2")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("landkodeAlfa2")]
        public string LandkodeAlfa2 { get; set; }
    }
}
