// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class NkrsyklusVitnemalsnavnAlleSprakQueryBuilder : GraphQlQueryBuilder<NkrsyklusVitnemalsnavnAlleSprakQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "en" },
            new() { Name = "nb" },
            new() { Name = "nn" },
            new() { Name = "se" }
        };

        protected override string TypeName => "NkrsyklusVitnemalsnavnAlleSprak";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder WithEn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("en", alias, [include, skip]);

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder ExceptEn() => ExceptField("en");

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder WithNb(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("nb", alias, [include, skip]);

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder ExceptNb() => ExceptField("nb");

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder WithNn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("nn", alias, [include, skip]);

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder ExceptNn() => ExceptField("nn");

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder WithSe(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("se", alias, [include, skip]);

        public NkrsyklusVitnemalsnavnAlleSprakQueryBuilder ExceptSe() => ExceptField("se");
    }
}
