// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettFagpersonGittPassInput : IGraphQlInputObject
    {
        private InputPropertyInfo _eierOrganisasjonskode;
        private InputPropertyInfo _pass;
        private InputPropertyInfo _fodselsdato;
        private InputPropertyInfo _kjonn;
        private InputPropertyInfo _fornavn;
        private InputPropertyInfo _etternavn;
        private InputPropertyInfo _folkeregistrertAdresse;
        private InputPropertyInfo _privatEpost;
        private InputPropertyInfo _feideBruker;
        private InputPropertyInfo _malform;
        private InputPropertyInfo _mobilTelefon;
        private InputPropertyInfo _privatTelefon;
        private InputPropertyInfo _arbeidsAdresse;
        private InputPropertyInfo _campus;
        private InputPropertyInfo _ansattVedOrganisasjonsenhet;
        private InputPropertyInfo _erEkstern;
        private InputPropertyInfo _ansattnummer;
        private InputPropertyInfo _stillingstittel;
        private InputPropertyInfo _rom;
        private InputPropertyInfo _arbeidsEpost;
        private InputPropertyInfo _fagpersonkategori;
        private InputPropertyInfo _institusjonsEpost;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("eierOrganisasjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("eierOrganisasjonskode")]
        public QueryBuilderParameter<string> EierOrganisasjonskode
        {
            get => (QueryBuilderParameter<string>)_eierOrganisasjonskode.Value;
            set => _eierOrganisasjonskode = new() { Name = "eierOrganisasjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("pass")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Passinnput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("pass")]
        public QueryBuilderParameter<Passinnput> Pass
        {
            get => (QueryBuilderParameter<Passinnput>)_pass.Value;
            set => _pass = new() { Name = "pass", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fodselsdato")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<object>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fodselsdato")]
        public QueryBuilderParameter<object> Fodselsdato
        {
            get => (QueryBuilderParameter<object>)_fodselsdato.Value;
            set => _fodselsdato = new() { Name = "fodselsdato", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kjonn")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Kjonn?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kjonn")]
        public QueryBuilderParameter<Kjonn?> Kjonn
        {
            get => (QueryBuilderParameter<Kjonn?>)_kjonn.Value;
            set => _kjonn = new() { Name = "kjonn", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fornavn")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fornavn")]
        public QueryBuilderParameter<string> Fornavn
        {
            get => (QueryBuilderParameter<string>)_fornavn.Value;
            set => _fornavn = new() { Name = "fornavn", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("etternavn")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("etternavn")]
        public QueryBuilderParameter<string> Etternavn
        {
            get => (QueryBuilderParameter<string>)_etternavn.Value;
            set => _etternavn = new() { Name = "etternavn", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("folkeregistrertAdresse")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<OpprettFagpersonForGittPassAdresseInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("folkeregistrertAdresse")]
        public QueryBuilderParameter<OpprettFagpersonForGittPassAdresseInput> FolkeregistrertAdresse
        {
            get => (QueryBuilderParameter<OpprettFagpersonForGittPassAdresseInput>)_folkeregistrertAdresse.Value;
            set => _folkeregistrertAdresse = new() { Name = "folkeregistrertAdresse", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("privatEpost")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("privatEpost")]
        public QueryBuilderParameter<string> PrivatEpost
        {
            get => (QueryBuilderParameter<string>)_privatEpost.Value;
            set => _privatEpost = new() { Name = "privatEpost", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("feideBruker")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("feideBruker")]
        public QueryBuilderParameter<string> FeideBruker
        {
            get => (QueryBuilderParameter<string>)_feideBruker.Value;
            set => _feideBruker = new() { Name = "feideBruker", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("malform")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<MaalformInput?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("malform")]
        public QueryBuilderParameter<MaalformInput?> Malform
        {
            get => (QueryBuilderParameter<MaalformInput?>)_malform.Value;
            set => _malform = new() { Name = "malform", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("mobilTelefon")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<OpprettFagpersonForGittPassTelefonnummerInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("mobilTelefon")]
        public QueryBuilderParameter<OpprettFagpersonForGittPassTelefonnummerInput> MobilTelefon
        {
            get => (QueryBuilderParameter<OpprettFagpersonForGittPassTelefonnummerInput>)_mobilTelefon.Value;
            set => _mobilTelefon = new() { Name = "mobilTelefon", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("privatTelefon")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<OpprettFagpersonForGittPassTelefonnummerInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("privatTelefon")]
        public QueryBuilderParameter<OpprettFagpersonForGittPassTelefonnummerInput> PrivatTelefon
        {
            get => (QueryBuilderParameter<OpprettFagpersonForGittPassTelefonnummerInput>)_privatTelefon.Value;
            set => _privatTelefon = new() { Name = "privatTelefon", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("arbeidsAdresse")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<OpprettFagpersonForGittPassAdresseInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("arbeidsAdresse")]
        public QueryBuilderParameter<OpprettFagpersonForGittPassAdresseInput> ArbeidsAdresse
        {
            get => (QueryBuilderParameter<OpprettFagpersonForGittPassAdresseInput>)_arbeidsAdresse.Value;
            set => _arbeidsAdresse = new() { Name = "arbeidsAdresse", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("campus")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("campus")]
        public QueryBuilderParameter<string> Campus
        {
            get => (QueryBuilderParameter<string>)_campus.Value;
            set => _campus = new() { Name = "campus", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("ansattVedOrganisasjonsenhet")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("ansattVedOrganisasjonsenhet")]
        public QueryBuilderParameter<string> AnsattVedOrganisasjonsenhet
        {
            get => (QueryBuilderParameter<string>)_ansattVedOrganisasjonsenhet.Value;
            set => _ansattVedOrganisasjonsenhet = new() { Name = "ansattVedOrganisasjonsenhet", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erEkstern")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erEkstern")]
        public QueryBuilderParameter<bool?> ErEkstern
        {
            get => (QueryBuilderParameter<bool?>)_erEkstern.Value;
            set => _erEkstern = new() { Name = "erEkstern", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("ansattnummer")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("ansattnummer")]
        public QueryBuilderParameter<string> Ansattnummer
        {
            get => (QueryBuilderParameter<string>)_ansattnummer.Value;
            set => _ansattnummer = new() { Name = "ansattnummer", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("stillingstittel")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<OpprettFapersonForGittFodselsnummerStillingstittelInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("stillingstittel")]
        public QueryBuilderParameter<OpprettFapersonForGittFodselsnummerStillingstittelInput> Stillingstittel
        {
            get => (QueryBuilderParameter<OpprettFapersonForGittFodselsnummerStillingstittelInput>)_stillingstittel.Value;
            set => _stillingstittel = new() { Name = "stillingstittel", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("rom")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("rom")]
        public QueryBuilderParameter<string> Rom
        {
            get => (QueryBuilderParameter<string>)_rom.Value;
            set => _rom = new() { Name = "rom", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("arbeidsEpost")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("arbeidsEpost")]
        public QueryBuilderParameter<string> ArbeidsEpost
        {
            get => (QueryBuilderParameter<string>)_arbeidsEpost.Value;
            set => _arbeidsEpost = new() { Name = "arbeidsEpost", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fagpersonkategori")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fagpersonkategori")]
        public QueryBuilderParameter<string> Fagpersonkategori
        {
            get => (QueryBuilderParameter<string>)_fagpersonkategori.Value;
            set => _fagpersonkategori = new() { Name = "fagpersonkategori", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("institusjonsEpost")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("institusjonsEpost")]
        public QueryBuilderParameter<string> InstitusjonsEpost
        {
            get => (QueryBuilderParameter<string>)_institusjonsEpost.Value;
            set => _institusjonsEpost = new() { Name = "institusjonsEpost", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_eierOrganisasjonskode.Name != null) yield return _eierOrganisasjonskode;
            if (_pass.Name != null) yield return _pass;
            if (_fodselsdato.Name != null) yield return _fodselsdato;
            if (_kjonn.Name != null) yield return _kjonn;
            if (_fornavn.Name != null) yield return _fornavn;
            if (_etternavn.Name != null) yield return _etternavn;
            if (_folkeregistrertAdresse.Name != null) yield return _folkeregistrertAdresse;
            if (_privatEpost.Name != null) yield return _privatEpost;
            if (_feideBruker.Name != null) yield return _feideBruker;
            if (_malform.Name != null) yield return _malform;
            if (_mobilTelefon.Name != null) yield return _mobilTelefon;
            if (_privatTelefon.Name != null) yield return _privatTelefon;
            if (_arbeidsAdresse.Name != null) yield return _arbeidsAdresse;
            if (_campus.Name != null) yield return _campus;
            if (_ansattVedOrganisasjonsenhet.Name != null) yield return _ansattVedOrganisasjonsenhet;
            if (_erEkstern.Name != null) yield return _erEkstern;
            if (_ansattnummer.Name != null) yield return _ansattnummer;
            if (_stillingstittel.Name != null) yield return _stillingstittel;
            if (_rom.Name != null) yield return _rom;
            if (_arbeidsEpost.Name != null) yield return _arbeidsEpost;
            if (_fagpersonkategori.Name != null) yield return _fagpersonkategori;
            if (_institusjonsEpost.Name != null) yield return _institusjonsEpost;
        }
    }
}
