// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettStudenterTerminInput : IGraphQlInputObject
    {
        private InputPropertyInfo _ar;
        private InputPropertyInfo _terminkode;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("ar")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("ar")]
        public QueryBuilderParameter<int?> Ar
        {
            get => (QueryBuilderParameter<int?>)_ar.Value;
            set => _ar = new() { Name = "ar", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminkode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Termintype?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminkode")]
        public QueryBuilderParameter<Termintype?> Terminkode
        {
            get => (QueryBuilderParameter<Termintype?>)_terminkode.Value;
            set => _terminkode = new() { Name = "terminkode", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_ar.Name != null) yield return _ar;
            if (_terminkode.Name != null) yield return _terminkode;
        }
    }
}
