// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettOpptaksgrupperForUndervisningsenheterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _undervisningsenhet;
        private InputPropertyInfo _opptaksgruppe;
        private InputPropertyInfo _antallTilbud;
        private InputPropertyInfo _poenggrenseForOpptak;
        private InputPropertyInfo _sorteringsretningForPoengskala;
        private InputPropertyInfo _kreverStudierett;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsenhet")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Guid?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsenhet")]
        public QueryBuilderParameter<Guid?> Undervisningsenhet
        {
            get => (QueryBuilderParameter<Guid?>)_undervisningsenhet.Value;
            set => _undervisningsenhet = new() { Name = "undervisningsenhet", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("opptaksgruppe")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Guid?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("opptaksgruppe")]
        public QueryBuilderParameter<Guid?> Opptaksgruppe
        {
            get => (QueryBuilderParameter<Guid?>)_opptaksgruppe.Value;
            set => _opptaksgruppe = new() { Name = "opptaksgruppe", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("antallTilbud")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("antallTilbud")]
        public QueryBuilderParameter<int?> AntallTilbud
        {
            get => (QueryBuilderParameter<int?>)_antallTilbud.Value;
            set => _antallTilbud = new() { Name = "antallTilbud", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("poenggrenseForOpptak")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<object>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("poenggrenseForOpptak")]
        public QueryBuilderParameter<object> PoenggrenseForOpptak
        {
            get => (QueryBuilderParameter<object>)_poenggrenseForOpptak.Value;
            set => _poenggrenseForOpptak = new() { Name = "poenggrenseForOpptak", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sorteringsretningForPoengskala")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<SorteringsretningForPoengskala?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("sorteringsretningForPoengskala")]
        public QueryBuilderParameter<SorteringsretningForPoengskala?> SorteringsretningForPoengskala
        {
            get => (QueryBuilderParameter<SorteringsretningForPoengskala?>)_sorteringsretningForPoengskala.Value;
            set => _sorteringsretningForPoengskala = new() { Name = "sorteringsretningForPoengskala", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kreverStudierett")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kreverStudierett")]
        public QueryBuilderParameter<bool?> KreverStudierett
        {
            get => (QueryBuilderParameter<bool?>)_kreverStudierett.Value;
            set => _kreverStudierett = new() { Name = "kreverStudierett", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_undervisningsenhet.Name != null) yield return _undervisningsenhet;
            if (_opptaksgruppe.Name != null) yield return _opptaksgruppe;
            if (_antallTilbud.Name != null) yield return _antallTilbud;
            if (_poenggrenseForOpptak.Name != null) yield return _poenggrenseForOpptak;
            if (_sorteringsretningForPoengskala.Name != null) yield return _sorteringsretningForPoengskala;
            if (_kreverStudierett.Name != null) yield return _kreverStudierett;
        }
    }
}
