// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettUndervisningsaktiviteterPartiInput : IGraphQlInputObject
    {
        private InputPropertyInfo _partinummer;
        private InputPropertyInfo _undervisningsdisiplinId;
        private InputPropertyInfo _undervisningsformId;
        private InputPropertyInfo _studentKanMeldeSegPaAktivitet;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("partinummer")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("partinummer")]
        public QueryBuilderParameter<string> Partinummer
        {
            get => (QueryBuilderParameter<string>)_partinummer.Value;
            set => _partinummer = new() { Name = "partinummer", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsdisiplinId")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Guid?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsdisiplinId")]
        public QueryBuilderParameter<Guid?> UndervisningsdisiplinId
        {
            get => (QueryBuilderParameter<Guid?>)_undervisningsdisiplinId.Value;
            set => _undervisningsdisiplinId = new() { Name = "undervisningsdisiplinId", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsformId")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Guid?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsformId")]
        public QueryBuilderParameter<Guid?> UndervisningsformId
        {
            get => (QueryBuilderParameter<Guid?>)_undervisningsformId.Value;
            set => _undervisningsformId = new() { Name = "undervisningsformId", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studentKanMeldeSegPaAktivitet")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studentKanMeldeSegPaAktivitet")]
        public QueryBuilderParameter<bool?> StudentKanMeldeSegPaAktivitet
        {
            get => (QueryBuilderParameter<bool?>)_studentKanMeldeSegPaAktivitet.Value;
            set => _studentKanMeldeSegPaAktivitet = new() { Name = "studentKanMeldeSegPaAktivitet", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_partinummer.Name != null) yield return _partinummer;
            if (_undervisningsdisiplinId.Name != null) yield return _undervisningsdisiplinId;
            if (_undervisningsformId.Name != null) yield return _undervisningsformId;
            if (_studentKanMeldeSegPaAktivitet.Name != null) yield return _studentKanMeldeSegPaAktivitet;
        }
    }
}
