// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettKlasserForKullPayloadQueryBuilder : GraphQlQueryBuilder<OpprettKlasserForKullPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "klasser", IsComplex = true, QueryBuilderType = typeof(KlasseQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(OpprettKlasserForKullErrorQueryBuilder) }
        };

        protected override string TypeName => "OpprettKlasserForKullPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public OpprettKlasserForKullPayloadQueryBuilder WithKlasser(KlasseQueryBuilder klasseQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("klasser", alias, klasseQueryBuilder, [include, skip]);

        public OpprettKlasserForKullPayloadQueryBuilder ExceptKlasser() => ExceptField("klasser");

        public OpprettKlasserForKullPayloadQueryBuilder WithErrors(OpprettKlasserForKullErrorQueryBuilder opprettKlasserForKullErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, opprettKlasserForKullErrorQueryBuilder, [include, skip]);

        public OpprettKlasserForKullPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
