// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettKullPayloadQueryBuilder : GraphQlQueryBuilder<OpprettKullPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "kull", IsComplex = true, QueryBuilderType = typeof(KullQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(OpprettKullErrorQueryBuilder) }
        };

        protected override string TypeName => "OpprettKullPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public OpprettKullPayloadQueryBuilder WithKull(KullQueryBuilder kullQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("kull", alias, kullQueryBuilder, [include, skip]);

        public OpprettKullPayloadQueryBuilder ExceptKull() => ExceptField("kull");

        public OpprettKullPayloadQueryBuilder WithErrors(OpprettKullErrorQueryBuilder opprettKullErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, opprettKullErrorQueryBuilder, [include, skip]);

        public OpprettKullPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
