// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettOpptaksgrupperForUndervisningsenheterPayloadQueryBuilder : GraphQlQueryBuilder<OpprettOpptaksgrupperForUndervisningsenheterPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "opptaksgrupper", IsComplex = true, QueryBuilderType = typeof(OpptaksgruppeForUndervisningsenhetQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(OpprettOpptaksgrupperForUndervisningsenheterErrorQueryBuilder) }
        };

        protected override string TypeName => "OpprettOpptaksgrupperForUndervisningsenheterPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public OpprettOpptaksgrupperForUndervisningsenheterPayloadQueryBuilder WithOpptaksgrupper(OpptaksgruppeForUndervisningsenhetQueryBuilder opptaksgruppeForUndervisningsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("opptaksgrupper", alias, opptaksgruppeForUndervisningsenhetQueryBuilder, [include, skip]);

        public OpprettOpptaksgrupperForUndervisningsenheterPayloadQueryBuilder ExceptOpptaksgrupper() => ExceptField("opptaksgrupper");

        public OpprettOpptaksgrupperForUndervisningsenheterPayloadQueryBuilder WithErrors(OpprettOpptaksgrupperForUndervisningsenheterErrorQueryBuilder opprettOpptaksgrupperForUndervisningsenheterErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, opprettOpptaksgrupperForUndervisningsenheterErrorQueryBuilder, [include, skip]);

        public OpprettOpptaksgrupperForUndervisningsenheterPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
