// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OpprettUndervisningsaktivitetsrollerPayloadQueryBuilder : GraphQlQueryBuilder<OpprettUndervisningsaktivitetsrollerPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "undervisningsaktivitetsroller", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetsrolleQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(OpprettUndervisningsaktivitetsrollerErrorQueryBuilder) }
        };

        protected override string TypeName => "OpprettUndervisningsaktivitetsrollerPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public OpprettUndervisningsaktivitetsrollerPayloadQueryBuilder WithUndervisningsaktivitetsroller(UndervisningsaktivitetsrolleQueryBuilder undervisningsaktivitetsrolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisningsaktivitetsroller", alias, undervisningsaktivitetsrolleQueryBuilder, [include, skip]);

        public OpprettUndervisningsaktivitetsrollerPayloadQueryBuilder ExceptUndervisningsaktivitetsroller() => ExceptField("undervisningsaktivitetsroller");

        public OpprettUndervisningsaktivitetsrollerPayloadQueryBuilder WithErrors(OpprettUndervisningsaktivitetsrollerErrorQueryBuilder opprettUndervisningsaktivitetsrollerErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, opprettUndervisningsaktivitetsrollerErrorQueryBuilder, [include, skip]);

        public OpprettUndervisningsaktivitetsrollerPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
