// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OrganisasjonsenhetskodeInput : IGraphQlInputObject
    {
        private InputPropertyInfo _organisasjonskode;
        private InputPropertyInfo _fakultetskode;
        private InputPropertyInfo _instituttkode;
        private InputPropertyInfo _gruppekode;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("organisasjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("organisasjonskode")]
        public QueryBuilderParameter<string> Organisasjonskode
        {
            get => (QueryBuilderParameter<string>)_organisasjonskode.Value;
            set => _organisasjonskode = new() { Name = "organisasjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fakultetskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fakultetskode")]
        public QueryBuilderParameter<string> Fakultetskode
        {
            get => (QueryBuilderParameter<string>)_fakultetskode.Value;
            set => _fakultetskode = new() { Name = "fakultetskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("instituttkode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("instituttkode")]
        public QueryBuilderParameter<string> Instituttkode
        {
            get => (QueryBuilderParameter<string>)_instituttkode.Value;
            set => _instituttkode = new() { Name = "instituttkode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("gruppekode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("gruppekode")]
        public QueryBuilderParameter<string> Gruppekode
        {
            get => (QueryBuilderParameter<string>)_gruppekode.Value;
            set => _gruppekode = new() { Name = "gruppekode", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_organisasjonskode.Name != null) yield return _organisasjonskode;
            if (_fakultetskode.Name != null) yield return _fakultetskode;
            if (_instituttkode.Name != null) yield return _instituttkode;
            if (_gruppekode.Name != null) yield return _gruppekode;
        }
    }
}
