// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class OrganisasjonsenhetPersonrollerConnectionQueryBuilder : GraphQlQueryBuilder<OrganisasjonsenhetPersonrollerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(OrganisasjonsenhetPersonrollerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(OrganisasjonsenhetsrolleQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "OrganisasjonsenhetPersonrollerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder WithEdges(OrganisasjonsenhetPersonrollerConnectionEdgeQueryBuilder organisasjonsenhetPersonrollerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, organisasjonsenhetPersonrollerConnectionEdgeQueryBuilder, [include, skip]);

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder WithNodes(OrganisasjonsenhetsrolleQueryBuilder organisasjonsenhetsrolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, organisasjonsenhetsrolleQueryBuilder, [include, skip]);

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public OrganisasjonsenhetPersonrollerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
