// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class PersonProfilFsSoknaderConnectionQueryBuilder : GraphQlQueryBuilder<PersonProfilFsSoknaderConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(PersonProfilFsSoknaderConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(FsSoknadQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "PersonProfilFsSoknaderConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public PersonProfilFsSoknaderConnectionQueryBuilder WithEdges(PersonProfilFsSoknaderConnectionEdgeQueryBuilder personProfilFsSoknaderConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, personProfilFsSoknaderConnectionEdgeQueryBuilder, [include, skip]);

        public PersonProfilFsSoknaderConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public PersonProfilFsSoknaderConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public PersonProfilFsSoknaderConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public PersonProfilFsSoknaderConnectionQueryBuilder WithNodes(FsSoknadQueryBuilder fsSoknadQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, fsSoknadQueryBuilder, [include, skip]);

        public PersonProfilFsSoknaderConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public PersonProfilFsSoknaderConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public PersonProfilFsSoknaderConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
