// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public enum PersonrolleAktivStatus
    {
        [EnumMember(Value = "FREMTIDIG")] Fremtidig,
        [EnumMember(Value = "AKTIV")] Aktiv,
        [EnumMember(Value = "AVSLUTTET")] Avsluttet
    }
}
