// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class PersonProfilDodsfallAnnullertQueryBuilder : GraphQlQueryBuilder<PersonProfilDodsfallAnnullertQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "PersonProfilDodsfallAnnullert";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public PersonProfilDodsfallAnnullertQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public PersonProfilDodsfallAnnullertQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public PersonProfilDodsfallAnnullertQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public PersonProfilDodsfallAnnullertQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public PersonProfilDodsfallAnnullertQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public PersonProfilDodsfallAnnullertQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");
    }
}
