// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class PersonProfilEndretFodselsnummerQueryBuilder : GraphQlQueryBuilder<PersonProfilEndretFodselsnummerQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) },
            new() { Name = "fodselsnummerendring", IsComplex = true, QueryBuilderType = typeof(FodselsnummerendringQueryBuilder) }
        };

        protected override string TypeName => "PersonProfilEndretFodselsnummer";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public PersonProfilEndretFodselsnummerQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public PersonProfilEndretFodselsnummerQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public PersonProfilEndretFodselsnummerQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public PersonProfilEndretFodselsnummerQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public PersonProfilEndretFodselsnummerQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public PersonProfilEndretFodselsnummerQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");

        public PersonProfilEndretFodselsnummerQueryBuilder WithFodselsnummerendring(FodselsnummerendringQueryBuilder fodselsnummerendringQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("fodselsnummerendring", alias, fodselsnummerendringQueryBuilder, [include, skip]);

        public PersonProfilEndretFodselsnummerQueryBuilder ExceptFodselsnummerendring() => ExceptField("fodselsnummerendring");
    }
}
