// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class ProgramStudierettPhdData
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("organisasjonsenhet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("organisasjonsenhet")]
        public Organisasjonsenhet Organisasjonsenhet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("beregnetSluttdato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("beregnetSluttdato")]
        public object BeregnetSluttdato { get; set; }
    }
}
