// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("ProtokollfoertEmnesamling")]
    public partial class ProtokollfoertEmnesamling : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emnesamling")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emnesamling")]
        public Emnesamling Emnesamling { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("oppnaddDato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("oppnaddDato")]
        public OppnaddEmnesamlingDato OppnaddDato { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("karakter")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("karakter")]
        public OppnaddKarakterEmnesamling Karakter { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("opprinneligLarested")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("opprinneligLarested")]
        public Organisasjon OpprinneligLarested { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erGyldig")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erGyldig")]
        public bool? ErGyldig { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("resultater")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("resultater")]
        public ICollection<Resultat> Resultater { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("oppnaddeKvalifikasjoner")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("oppnaddeKvalifikasjoner")]
        public ICollection<OppnaddKvalifikasjon> OppnaddeKvalifikasjoner { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("children")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("children")]
        public ICollection<ProtokollfoertEmnesamling> Children { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("parents")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("parents")]
        public ICollection<ProtokollfoertEmnesamling> Parents { get; set; }
    }
}
