// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class PubliseringsklartStudieprogramTerminInput : IGraphQlInputObject
    {
        private InputPropertyInfo _arstall;
        private InputPropertyInfo _terminbetegnelse;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("arstall")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("arstall")]
        public QueryBuilderParameter<int?> Arstall
        {
            get => (QueryBuilderParameter<int?>)_arstall.Value;
            set => _arstall = new() { Name = "arstall", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminbetegnelse")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminbetegnelse")]
        public QueryBuilderParameter<string> Terminbetegnelse
        {
            get => (QueryBuilderParameter<string>)_terminbetegnelse.Value;
            set => _terminbetegnelse = new() { Name = "terminbetegnelse", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_arstall.Name != null) yield return _arstall;
            if (_terminbetegnelse.Name != null) yield return _terminbetegnelse;
        }
    }
}
