// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryKlassemedlemskapshendelserConnectionQueryBuilder : GraphQlQueryBuilder<QueryKlassemedlemskapshendelserConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryKlassemedlemskapshendelserConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(KlassemedlemskapshendelseQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryKlassemedlemskapshendelserConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder WithEdges(QueryKlassemedlemskapshendelserConnectionEdgeQueryBuilder queryKlassemedlemskapshendelserConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryKlassemedlemskapshendelserConnectionEdgeQueryBuilder, [include, skip]);

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder WithNodes(KlassemedlemskapshendelseQueryBuilder klassemedlemskapshendelseQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, klassemedlemskapshendelseQueryBuilder, [include, skip]);

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryKlassemedlemskapshendelserConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
