// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryGodkjenningsinstanserConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryGodkjenningsinstanserConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(GodkjenninginstansQueryBuilder) }
        };

        protected override string TypeName => "QueryGodkjenningsinstanserConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryGodkjenningsinstanserConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryGodkjenningsinstanserConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryGodkjenningsinstanserConnectionEdgeQueryBuilder WithNode(GodkjenninginstansQueryBuilder godkjenninginstansQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, godkjenninginstansQueryBuilder, [include, skip]);

        public QueryGodkjenningsinstanserConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
