// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryKlasserConnectionQueryBuilder : GraphQlQueryBuilder<QueryKlasserConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryKlasserConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(KlasseQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryKlasserConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryKlasserConnectionQueryBuilder WithEdges(QueryKlasserConnectionEdgeQueryBuilder queryKlasserConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryKlasserConnectionEdgeQueryBuilder, [include, skip]);

        public QueryKlasserConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryKlasserConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryKlasserConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryKlasserConnectionQueryBuilder WithNodes(KlasseQueryBuilder klasseQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, klasseQueryBuilder, [include, skip]);

        public QueryKlasserConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryKlasserConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryKlasserConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
