// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryTidsenheterConnectionQueryBuilder : GraphQlQueryBuilder<QueryTidsenheterConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryTidsenheterConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(TidsenhetQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryTidsenheterConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryTidsenheterConnectionQueryBuilder WithEdges(QueryTidsenheterConnectionEdgeQueryBuilder queryTidsenheterConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryTidsenheterConnectionEdgeQueryBuilder, [include, skip]);

        public QueryTidsenheterConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryTidsenheterConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryTidsenheterConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryTidsenheterConnectionQueryBuilder WithNodes(TidsenhetQueryBuilder tidsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, tidsenhetQueryBuilder, [include, skip]);

        public QueryTidsenheterConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryTidsenheterConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryTidsenheterConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
