// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryEmnerollerFilterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _eierOrganisasjonskode;
        private InputPropertyInfo _emner;
        private InputPropertyInfo _tjenestenummerForLms;
        private InputPropertyInfo _personProfiler;
        private InputPropertyInfo _aktivInnenforPeriode;
        private InputPropertyInfo _imsRoller;
        private InputPropertyInfo _fsRoller;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("eierOrganisasjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("eierOrganisasjonskode")]
        public QueryBuilderParameter<string> EierOrganisasjonskode
        {
            get => (QueryBuilderParameter<string>)_eierOrganisasjonskode.Value;
            set => _eierOrganisasjonskode = new() { Name = "eierOrganisasjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emner")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Guid>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emner")]
        public QueryBuilderParameter<ICollection<Guid>> Emner
        {
            get => (QueryBuilderParameter<ICollection<Guid>>)_emner.Value;
            set => _emner = new() { Name = "emner", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tjenestenummerForLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tjenestenummerForLms")]
        public QueryBuilderParameter<string> TjenestenummerForLms
        {
            get => (QueryBuilderParameter<string>)_tjenestenummerForLms.Value;
            set => _tjenestenummerForLms = new() { Name = "tjenestenummerForLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("personProfiler")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Guid>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("personProfiler")]
        public QueryBuilderParameter<ICollection<Guid>> PersonProfiler
        {
            get => (QueryBuilderParameter<ICollection<Guid>>)_personProfiler.Value;
            set => _personProfiler = new() { Name = "personProfiler", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("aktivInnenforPeriode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<EmneRolleDatoperiodeInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("aktivInnenforPeriode")]
        public QueryBuilderParameter<EmneRolleDatoperiodeInput> AktivInnenforPeriode
        {
            get => (QueryBuilderParameter<EmneRolleDatoperiodeInput>)_aktivInnenforPeriode.Value;
            set => _aktivInnenforPeriode = new() { Name = "aktivInnenforPeriode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("imsRoller")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<ImsRolle?>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("imsRoller")]
        public QueryBuilderParameter<ICollection<ImsRolle?>> ImsRoller
        {
            get => (QueryBuilderParameter<ICollection<ImsRolle?>>)_imsRoller.Value;
            set => _imsRoller = new() { Name = "imsRoller", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fsRoller")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Guid>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fsRoller")]
        public QueryBuilderParameter<ICollection<Guid>> FsRoller
        {
            get => (QueryBuilderParameter<ICollection<Guid>>)_fsRoller.Value;
            set => _fsRoller = new() { Name = "fsRoller", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_eierOrganisasjonskode.Name != null) yield return _eierOrganisasjonskode;
            if (_emner.Name != null) yield return _emner;
            if (_tjenestenummerForLms.Name != null) yield return _tjenestenummerForLms;
            if (_personProfiler.Name != null) yield return _personProfiler;
            if (_aktivInnenforPeriode.Name != null) yield return _aktivInnenforPeriode;
            if (_imsRoller.Name != null) yield return _imsRoller;
            if (_fsRoller.Name != null) yield return _fsRoller;
        }
    }
}
