// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryEmneSoknadHendelserConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryEmneSoknadHendelserConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(EmneSoknadshendelseQueryBuilder) }
        };

        protected override string TypeName => "QueryEmneSoknadHendelserConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryEmneSoknadHendelserConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryEmneSoknadHendelserConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryEmneSoknadHendelserConnectionEdgeQueryBuilder WithNode(EmneSoknadshendelseQueryBuilder emneSoknadshendelseQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, emneSoknadshendelseQueryBuilder, [include, skip]);

        public QueryEmneSoknadHendelserConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
