// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryKullrollerFilterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _eierOrganisasjonskode;
        private InputPropertyInfo _studieprogrammer;
        private InputPropertyInfo _kullSkalEksporteresTilLms;
        private InputPropertyInfo _tjenestenummerForLms;
        private InputPropertyInfo _personProfiler;
        private InputPropertyInfo _kull;
        private InputPropertyInfo _aktivInnenforPeriode;
        private InputPropertyInfo _imsRoller;
        private InputPropertyInfo _studieprogramSkalEksporteresTilLms;
        private InputPropertyInfo _kullErAktiv;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("eierOrganisasjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("eierOrganisasjonskode")]
        public QueryBuilderParameter<string> EierOrganisasjonskode
        {
            get => (QueryBuilderParameter<string>)_eierOrganisasjonskode.Value;
            set => _eierOrganisasjonskode = new() { Name = "eierOrganisasjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogrammer")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Guid>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogrammer")]
        public QueryBuilderParameter<ICollection<Guid>> Studieprogrammer
        {
            get => (QueryBuilderParameter<ICollection<Guid>>)_studieprogrammer.Value;
            set => _studieprogrammer = new() { Name = "studieprogrammer", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kullSkalEksporteresTilLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kullSkalEksporteresTilLms")]
        public QueryBuilderParameter<bool?> KullSkalEksporteresTilLms
        {
            get => (QueryBuilderParameter<bool?>)_kullSkalEksporteresTilLms.Value;
            set => _kullSkalEksporteresTilLms = new() { Name = "kullSkalEksporteresTilLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tjenestenummerForLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tjenestenummerForLms")]
        public QueryBuilderParameter<string> TjenestenummerForLms
        {
            get => (QueryBuilderParameter<string>)_tjenestenummerForLms.Value;
            set => _tjenestenummerForLms = new() { Name = "tjenestenummerForLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("personProfiler")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Guid>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("personProfiler")]
        public QueryBuilderParameter<ICollection<Guid>> PersonProfiler
        {
            get => (QueryBuilderParameter<ICollection<Guid>>)_personProfiler.Value;
            set => _personProfiler = new() { Name = "personProfiler", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kull")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Guid>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kull")]
        public QueryBuilderParameter<ICollection<Guid>> Kull
        {
            get => (QueryBuilderParameter<ICollection<Guid>>)_kull.Value;
            set => _kull = new() { Name = "kull", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("aktivInnenforPeriode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<QueryKullrollerDatoperiodeInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("aktivInnenforPeriode")]
        public QueryBuilderParameter<QueryKullrollerDatoperiodeInput> AktivInnenforPeriode
        {
            get => (QueryBuilderParameter<QueryKullrollerDatoperiodeInput>)_aktivInnenforPeriode.Value;
            set => _aktivInnenforPeriode = new() { Name = "aktivInnenforPeriode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("imsRoller")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<ImsRolle?>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("imsRoller")]
        public QueryBuilderParameter<ICollection<ImsRolle?>> ImsRoller
        {
            get => (QueryBuilderParameter<ICollection<ImsRolle?>>)_imsRoller.Value;
            set => _imsRoller = new() { Name = "imsRoller", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogramSkalEksporteresTilLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogramSkalEksporteresTilLms")]
        public QueryBuilderParameter<bool?> StudieprogramSkalEksporteresTilLms
        {
            get => (QueryBuilderParameter<bool?>)_studieprogramSkalEksporteresTilLms.Value;
            set => _studieprogramSkalEksporteresTilLms = new() { Name = "studieprogramSkalEksporteresTilLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kullErAktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<bool?>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kullErAktiv")]
        public QueryBuilderParameter<ICollection<bool?>> KullErAktiv
        {
            get => (QueryBuilderParameter<ICollection<bool?>>)_kullErAktiv.Value;
            set => _kullErAktiv = new() { Name = "kullErAktiv", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_eierOrganisasjonskode.Name != null) yield return _eierOrganisasjonskode;
            if (_studieprogrammer.Name != null) yield return _studieprogrammer;
            if (_kullSkalEksporteresTilLms.Name != null) yield return _kullSkalEksporteresTilLms;
            if (_tjenestenummerForLms.Name != null) yield return _tjenestenummerForLms;
            if (_personProfiler.Name != null) yield return _personProfiler;
            if (_kull.Name != null) yield return _kull;
            if (_aktivInnenforPeriode.Name != null) yield return _aktivInnenforPeriode;
            if (_imsRoller.Name != null) yield return _imsRoller;
            if (_studieprogramSkalEksporteresTilLms.Name != null) yield return _studieprogramSkalEksporteresTilLms;
            if (_kullErAktiv.Name != null) yield return _kullErAktiv;
        }
    }
}
