// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryLandConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryLandConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(LandQueryBuilder) }
        };

        protected override string TypeName => "QueryLandConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryLandConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryLandConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryLandConnectionEdgeQueryBuilder WithNode(LandQueryBuilder landQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, landQueryBuilder, [include, skip]);

        public QueryLandConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
