// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryPersonProfilerConnectionQueryBuilder : GraphQlQueryBuilder<QueryPersonProfilerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryPersonProfilerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryPersonProfilerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryPersonProfilerConnectionQueryBuilder WithEdges(QueryPersonProfilerConnectionEdgeQueryBuilder queryPersonProfilerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryPersonProfilerConnectionEdgeQueryBuilder, [include, skip]);

        public QueryPersonProfilerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryPersonProfilerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryPersonProfilerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryPersonProfilerConnectionQueryBuilder WithNodes(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, personProfilQueryBuilder, [include, skip]);

        public QueryPersonProfilerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryPersonProfilerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryPersonProfilerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
