// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryKlassemedlemskapshendelserFilterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _eierOrganisasjonskode;
        private InputPropertyInfo _hendelsestyper;
        private InputPropertyInfo _studieprogramErAktiv;
        private InputPropertyInfo _studieprogramSkalEksporteresTilLms;
        private InputPropertyInfo _tjenestenummerForLms;
        private InputPropertyInfo _erAktiv;
        private InputPropertyInfo _klasseErAktiv;
        private InputPropertyInfo _klasseSkalEksporteresTilLms;
        private InputPropertyInfo _kullErAktiv;
        private InputPropertyInfo _kullSkalEksporteresTilLms;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("eierOrganisasjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("eierOrganisasjonskode")]
        public QueryBuilderParameter<string> EierOrganisasjonskode
        {
            get => (QueryBuilderParameter<string>)_eierOrganisasjonskode.Value;
            set => _eierOrganisasjonskode = new() { Name = "eierOrganisasjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("hendelsestyper")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<Klassemedlemskapshendelsestype>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("hendelsestyper")]
        public QueryBuilderParameter<ICollection<Klassemedlemskapshendelsestype>> Hendelsestyper
        {
            get => (QueryBuilderParameter<ICollection<Klassemedlemskapshendelsestype>>)_hendelsestyper.Value;
            set => _hendelsestyper = new() { Name = "hendelsestyper", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogramErAktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogramErAktiv")]
        public QueryBuilderParameter<bool?> StudieprogramErAktiv
        {
            get => (QueryBuilderParameter<bool?>)_studieprogramErAktiv.Value;
            set => _studieprogramErAktiv = new() { Name = "studieprogramErAktiv", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogramSkalEksporteresTilLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogramSkalEksporteresTilLms")]
        public QueryBuilderParameter<bool?> StudieprogramSkalEksporteresTilLms
        {
            get => (QueryBuilderParameter<bool?>)_studieprogramSkalEksporteresTilLms.Value;
            set => _studieprogramSkalEksporteresTilLms = new() { Name = "studieprogramSkalEksporteresTilLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tjenestenummerForLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tjenestenummerForLms")]
        public QueryBuilderParameter<string> TjenestenummerForLms
        {
            get => (QueryBuilderParameter<string>)_tjenestenummerForLms.Value;
            set => _tjenestenummerForLms = new() { Name = "tjenestenummerForLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erAktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erAktiv")]
        public QueryBuilderParameter<bool?> ErAktiv
        {
            get => (QueryBuilderParameter<bool?>)_erAktiv.Value;
            set => _erAktiv = new() { Name = "erAktiv", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("klasseErAktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("klasseErAktiv")]
        public QueryBuilderParameter<bool?> KlasseErAktiv
        {
            get => (QueryBuilderParameter<bool?>)_klasseErAktiv.Value;
            set => _klasseErAktiv = new() { Name = "klasseErAktiv", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("klasseSkalEksporteresTilLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("klasseSkalEksporteresTilLms")]
        public QueryBuilderParameter<bool?> KlasseSkalEksporteresTilLms
        {
            get => (QueryBuilderParameter<bool?>)_klasseSkalEksporteresTilLms.Value;
            set => _klasseSkalEksporteresTilLms = new() { Name = "klasseSkalEksporteresTilLms", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kullErAktiv")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kullErAktiv")]
        public QueryBuilderParameter<bool?> KullErAktiv
        {
            get => (QueryBuilderParameter<bool?>)_kullErAktiv.Value;
            set => _kullErAktiv = new() { Name = "kullErAktiv", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kullSkalEksporteresTilLms")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kullSkalEksporteresTilLms")]
        public QueryBuilderParameter<bool?> KullSkalEksporteresTilLms
        {
            get => (QueryBuilderParameter<bool?>)_kullSkalEksporteresTilLms.Value;
            set => _kullSkalEksporteresTilLms = new() { Name = "kullSkalEksporteresTilLms", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_eierOrganisasjonskode.Name != null) yield return _eierOrganisasjonskode;
            if (_hendelsestyper.Name != null) yield return _hendelsestyper;
            if (_studieprogramErAktiv.Name != null) yield return _studieprogramErAktiv;
            if (_studieprogramSkalEksporteresTilLms.Name != null) yield return _studieprogramSkalEksporteresTilLms;
            if (_tjenestenummerForLms.Name != null) yield return _tjenestenummerForLms;
            if (_erAktiv.Name != null) yield return _erAktiv;
            if (_klasseErAktiv.Name != null) yield return _klasseErAktiv;
            if (_klasseSkalEksporteresTilLms.Name != null) yield return _klasseSkalEksporteresTilLms;
            if (_kullErAktiv.Name != null) yield return _kullErAktiv;
            if (_kullSkalEksporteresTilLms.Name != null) yield return _kullSkalEksporteresTilLms;
        }
    }
}
