// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryStudieoppbygningerConnectionQueryBuilder : GraphQlQueryBuilder<QueryStudieoppbygningerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryStudieoppbygningerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(StudieoppbygningForKullQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryStudieoppbygningerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryStudieoppbygningerConnectionQueryBuilder WithEdges(QueryStudieoppbygningerConnectionEdgeQueryBuilder queryStudieoppbygningerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryStudieoppbygningerConnectionEdgeQueryBuilder, [include, skip]);

        public QueryStudieoppbygningerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryStudieoppbygningerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryStudieoppbygningerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryStudieoppbygningerConnectionQueryBuilder WithNodes(StudieoppbygningForKullQueryBuilder studieoppbygningForKullQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, studieoppbygningForKullQueryBuilder, [include, skip]);

        public QueryStudieoppbygningerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryStudieoppbygningerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryStudieoppbygningerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
