// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QuerySensurkommisjonerConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QuerySensurkommisjonerConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(SensurkommisjonQueryBuilder) }
        };

        protected override string TypeName => "QuerySensurkommisjonerConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QuerySensurkommisjonerConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QuerySensurkommisjonerConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QuerySensurkommisjonerConnectionEdgeQueryBuilder WithNode(SensurkommisjonQueryBuilder sensurkommisjonQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, sensurkommisjonQueryBuilder, [include, skip]);

        public QuerySensurkommisjonerConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
