// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryVurderingsenheterConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryVurderingsenheterConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(VurderingsenhetQueryBuilder) }
        };

        protected override string TypeName => "QueryVurderingsenheterConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryVurderingsenheterConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryVurderingsenheterConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryVurderingsenheterConnectionEdgeQueryBuilder WithNode(VurderingsenhetQueryBuilder vurderingsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, vurderingsenhetQueryBuilder, [include, skip]);

        public QueryVurderingsenheterConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
