// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryStudieprogramV2ConnectionQueryBuilder : GraphQlQueryBuilder<QueryStudieprogramV2ConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryStudieprogramV2ConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(StudieprogramQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryStudieprogramV2Connection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryStudieprogramV2ConnectionQueryBuilder WithEdges(QueryStudieprogramV2ConnectionEdgeQueryBuilder queryStudieprogramV2ConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryStudieprogramV2ConnectionEdgeQueryBuilder, [include, skip]);

        public QueryStudieprogramV2ConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryStudieprogramV2ConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryStudieprogramV2ConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryStudieprogramV2ConnectionQueryBuilder WithNodes(StudieprogramQueryBuilder studieprogramQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, studieprogramQueryBuilder, [include, skip]);

        public QueryStudieprogramV2ConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryStudieprogramV2ConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryStudieprogramV2ConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
