// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryFagpersonerConnectionQueryBuilder : GraphQlQueryBuilder<QueryFagpersonerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryFagpersonerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(FagpersonVedLarestedQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryFagpersonerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryFagpersonerConnectionQueryBuilder WithEdges(QueryFagpersonerConnectionEdgeQueryBuilder queryFagpersonerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryFagpersonerConnectionEdgeQueryBuilder, [include, skip]);

        public QueryFagpersonerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryFagpersonerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryFagpersonerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryFagpersonerConnectionQueryBuilder WithNodes(FagpersonVedLarestedQueryBuilder fagpersonVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, fagpersonVedLarestedQueryBuilder, [include, skip]);

        public QueryFagpersonerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryFagpersonerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryFagpersonerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
