// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryPersonProfilerConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryPersonProfilerConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "QueryPersonProfilerConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryPersonProfilerConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryPersonProfilerConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryPersonProfilerConnectionEdgeQueryBuilder WithNode(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, personProfilQueryBuilder, [include, skip]);

        public QueryPersonProfilerConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
