// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryEvuKursConnectionQueryBuilder : GraphQlQueryBuilder<QueryEvuKursConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryEvuKursConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(EvuKursQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryEvuKursConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryEvuKursConnectionQueryBuilder WithEdges(QueryEvuKursConnectionEdgeQueryBuilder queryEvuKursConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryEvuKursConnectionEdgeQueryBuilder, [include, skip]);

        public QueryEvuKursConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryEvuKursConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryEvuKursConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryEvuKursConnectionQueryBuilder WithNodes(EvuKursQueryBuilder evuKursQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, evuKursQueryBuilder, [include, skip]);

        public QueryEvuKursConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryEvuKursConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryEvuKursConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
