// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryVurderingsresultatstatuserConnectionQueryBuilder : GraphQlQueryBuilder<QueryVurderingsresultatstatuserConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryVurderingsresultatstatuserConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(VurderingsresultatstatusQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryVurderingsresultatstatuserConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryVurderingsresultatstatuserConnectionQueryBuilder WithEdges(QueryVurderingsresultatstatuserConnectionEdgeQueryBuilder queryVurderingsresultatstatuserConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryVurderingsresultatstatuserConnectionEdgeQueryBuilder, [include, skip]);

        public QueryVurderingsresultatstatuserConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryVurderingsresultatstatuserConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryVurderingsresultatstatuserConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryVurderingsresultatstatuserConnectionQueryBuilder WithNodes(VurderingsresultatstatusQueryBuilder vurderingsresultatstatusQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, vurderingsresultatstatusQueryBuilder, [include, skip]);

        public QueryVurderingsresultatstatuserConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryVurderingsresultatstatuserConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryVurderingsresultatstatuserConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
