// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryStudieprogramrollerConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryStudieprogramrollerConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(StudieprogramrolleQueryBuilder) }
        };

        protected override string TypeName => "QueryStudieprogramrollerConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryStudieprogramrollerConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryStudieprogramrollerConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryStudieprogramrollerConnectionEdgeQueryBuilder WithNode(StudieprogramrolleQueryBuilder studieprogramrolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, studieprogramrolleQueryBuilder, [include, skip]);

        public QueryStudieprogramrollerConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
