// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryKlasserollerConnectionQueryBuilder : GraphQlQueryBuilder<QueryKlasserollerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryKlasserollerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(KlasserolleQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryKlasserollerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryKlasserollerConnectionQueryBuilder WithEdges(QueryKlasserollerConnectionEdgeQueryBuilder queryKlasserollerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryKlasserollerConnectionEdgeQueryBuilder, [include, skip]);

        public QueryKlasserollerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryKlasserollerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryKlasserollerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryKlasserollerConnectionQueryBuilder WithNodes(KlasserolleQueryBuilder klasserolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, klasserolleQueryBuilder, [include, skip]);

        public QueryKlasserollerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryKlasserollerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryKlasserollerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
