// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryEmneStudieretterConnectionQueryBuilder : GraphQlQueryBuilder<QueryEmneStudieretterConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryEmneStudieretterConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(EmneStudierettQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryEmneStudieretterConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryEmneStudieretterConnectionQueryBuilder WithEdges(QueryEmneStudieretterConnectionEdgeQueryBuilder queryEmneStudieretterConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryEmneStudieretterConnectionEdgeQueryBuilder, [include, skip]);

        public QueryEmneStudieretterConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryEmneStudieretterConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryEmneStudieretterConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryEmneStudieretterConnectionQueryBuilder WithNodes(EmneStudierettQueryBuilder emneStudierettQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, emneStudierettQueryBuilder, [include, skip]);

        public QueryEmneStudieretterConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryEmneStudieretterConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryEmneStudieretterConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
