// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QuerySemesterregistreringerConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QuerySemesterregistreringerConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(SemesterregistreringQueryBuilder) }
        };

        protected override string TypeName => "QuerySemesterregistreringerConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QuerySemesterregistreringerConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QuerySemesterregistreringerConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QuerySemesterregistreringerConnectionEdgeQueryBuilder WithNode(SemesterregistreringQueryBuilder semesterregistreringQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, semesterregistreringQueryBuilder, [include, skip]);

        public QuerySemesterregistreringerConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
