// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryStudentStatuserConnectionQueryBuilder : GraphQlQueryBuilder<QueryStudentStatuserConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryStudentStatuserConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(StudentstatusQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryStudentStatuserConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryStudentStatuserConnectionQueryBuilder WithEdges(QueryStudentStatuserConnectionEdgeQueryBuilder queryStudentStatuserConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryStudentStatuserConnectionEdgeQueryBuilder, [include, skip]);

        public QueryStudentStatuserConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryStudentStatuserConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryStudentStatuserConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryStudentStatuserConnectionQueryBuilder WithNodes(StudentstatusQueryBuilder studentstatusQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, studentstatusQueryBuilder, [include, skip]);

        public QueryStudentStatuserConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryStudentStatuserConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryStudentStatuserConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
