// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder : GraphQlQueryBuilder<QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryMeldingerOmFodselsnummerendringConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(MeldingOmFodselsnummerendringQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryMeldingerOmFodselsnummerendringConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder WithEdges(QueryMeldingerOmFodselsnummerendringConnectionEdgeQueryBuilder queryMeldingerOmFodselsnummerendringConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryMeldingerOmFodselsnummerendringConnectionEdgeQueryBuilder, [include, skip]);

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder WithNodes(MeldingOmFodselsnummerendringQueryBuilder meldingOmFodselsnummerendringQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, meldingOmFodselsnummerendringQueryBuilder, [include, skip]);

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryMeldingerOmFodselsnummerendringConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
