// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryStudierettstatuserConnectionQueryBuilder : GraphQlQueryBuilder<QueryStudierettstatuserConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryStudierettstatuserConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(StudierettstatusQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryStudierettstatuserConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryStudierettstatuserConnectionQueryBuilder WithEdges(QueryStudierettstatuserConnectionEdgeQueryBuilder queryStudierettstatuserConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryStudierettstatuserConnectionEdgeQueryBuilder, [include, skip]);

        public QueryStudierettstatuserConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryStudierettstatuserConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryStudierettstatuserConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryStudierettstatuserConnectionQueryBuilder WithNodes(StudierettstatusQueryBuilder studierettstatusQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, studierettstatusQueryBuilder, [include, skip]);

        public QueryStudierettstatuserConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryStudierettstatuserConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryStudierettstatuserConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
