// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryTimeplanrollerConnectionQueryBuilder : GraphQlQueryBuilder<QueryTimeplanrollerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryTimeplanrollerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(TimeplanrolleQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryTimeplanrollerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryTimeplanrollerConnectionQueryBuilder WithEdges(QueryTimeplanrollerConnectionEdgeQueryBuilder queryTimeplanrollerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryTimeplanrollerConnectionEdgeQueryBuilder, [include, skip]);

        public QueryTimeplanrollerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryTimeplanrollerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryTimeplanrollerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryTimeplanrollerConnectionQueryBuilder WithNodes(TimeplanrolleQueryBuilder timeplanrolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, timeplanrolleQueryBuilder, [include, skip]);

        public QueryTimeplanrollerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryTimeplanrollerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryTimeplanrollerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
