// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryKlassemedlemskapConnectionQueryBuilder : GraphQlQueryBuilder<QueryKlassemedlemskapConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(QueryKlassemedlemskapConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(KlassemedlemskapQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "QueryKlassemedlemskapConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryKlassemedlemskapConnectionQueryBuilder WithEdges(QueryKlassemedlemskapConnectionEdgeQueryBuilder queryKlassemedlemskapConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, queryKlassemedlemskapConnectionEdgeQueryBuilder, [include, skip]);

        public QueryKlassemedlemskapConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public QueryKlassemedlemskapConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public QueryKlassemedlemskapConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public QueryKlassemedlemskapConnectionQueryBuilder WithNodes(KlassemedlemskapQueryBuilder klassemedlemskapQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, klassemedlemskapQueryBuilder, [include, skip]);

        public QueryKlassemedlemskapConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public QueryKlassemedlemskapConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public QueryKlassemedlemskapConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
