// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryTimeplanrollehendelserConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryTimeplanrollehendelserConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(TimeplanrollehendelseQueryBuilder) }
        };

        protected override string TypeName => "QueryTimeplanrollehendelserConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryTimeplanrollehendelserConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryTimeplanrollehendelserConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryTimeplanrollehendelserConnectionEdgeQueryBuilder WithNode(TimeplanrollehendelseQueryBuilder timeplanrollehendelseQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, timeplanrollehendelseQueryBuilder, [include, skip]);

        public QueryTimeplanrollehendelserConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
