// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryFodselsnummerendringerConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryFodselsnummerendringerConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(FodselsnummerendringQueryBuilder) }
        };

        protected override string TypeName => "QueryFodselsnummerendringerConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryFodselsnummerendringerConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryFodselsnummerendringerConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryFodselsnummerendringerConnectionEdgeQueryBuilder WithNode(FodselsnummerendringQueryBuilder fodselsnummerendringQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, fodselsnummerendringQueryBuilder, [include, skip]);

        public QueryFodselsnummerendringerConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
