// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class QueryStudietilpasningstyperConnectionEdgeQueryBuilder : GraphQlQueryBuilder<QueryStudietilpasningstyperConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(StudietilpasningstypeQueryBuilder) }
        };

        protected override string TypeName => "QueryStudietilpasningstyperConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public QueryStudietilpasningstyperConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public QueryStudietilpasningstyperConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public QueryStudietilpasningstyperConnectionEdgeQueryBuilder WithNode(StudietilpasningstypeQueryBuilder studietilpasningstypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, studietilpasningstypeQueryBuilder, [include, skip]);

        public QueryStudietilpasningstyperConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
