// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class ReferenceElement : IGraphQlInputObject
    {
        private InputPropertyInfo _table;
        private InputPropertyInfo _key;
        private InputPropertyInfo _condition;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("table")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("table")]
        public QueryBuilderParameter<string> Table
        {
            get => (QueryBuilderParameter<string>)_table.Value;
            set => _table = new() { Name = "table", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("key")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("key")]
        public QueryBuilderParameter<string> Key
        {
            get => (QueryBuilderParameter<string>)_key.Value;
            set => _key = new() { Name = "key", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("condition")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ExternalCodeReference>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public QueryBuilderParameter<ExternalCodeReference> Condition
        {
            get => (QueryBuilderParameter<ExternalCodeReference>)_condition.Value;
            set => _condition = new() { Name = "condition", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_table.Name != null) yield return _table;
            if (_key.Name != null) yield return _key;
            if (_condition.Name != null) yield return _condition;
        }
    }
}
