// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class RegistrerPermisjonForStudenterErrorQueryBuilder : GraphQlQueryBuilder<RegistrerPermisjonForStudenterErrorQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata = [];

        public RegistrerPermisjonForStudenterErrorQueryBuilder() => WithTypeName();

        protected override string TypeName => "RegistrerPermisjonForStudenterError";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public RegistrerPermisjonForStudenterErrorQueryBuilder WithUgyldigInputFragment(UgyldigInputQueryBuilder ugyldigInputQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(ugyldigInputQueryBuilder, [include, skip]);

        public RegistrerPermisjonForStudenterErrorQueryBuilder WithUgyldigPermisjonsperiodeFragment(UgyldigPermisjonsperiodeQueryBuilder ugyldigPermisjonsperiodeQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(ugyldigPermisjonsperiodeQueryBuilder, [include, skip]);
    }
}
