// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class RegistreringsformQueryBuilder : GraphQlQueryBuilder<RegistreringsformQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(RegistreringsformnavnAlleSprakQueryBuilder) },
            new() { Name = "erFelleskode" },
            new() { Name = "erAktiv" }
        };

        protected override string TypeName => "Registreringsform";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public RegistreringsformQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public RegistreringsformQueryBuilder ExceptId() => ExceptField("id");

        public RegistreringsformQueryBuilder WithNavnAlleSprak(RegistreringsformnavnAlleSprakQueryBuilder registreringsformnavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, registreringsformnavnAlleSprakQueryBuilder, [include, skip]);

        public RegistreringsformQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");

        public RegistreringsformQueryBuilder WithErFelleskode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erFelleskode", alias, [include, skip]);

        public RegistreringsformQueryBuilder ExceptErFelleskode() => ExceptField("erFelleskode");

        public RegistreringsformQueryBuilder WithErAktiv(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erAktiv", alias, [include, skip]);

        public RegistreringsformQueryBuilder ExceptErAktiv() => ExceptField("erAktiv");
    }
}
