// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class RegistrerFellesUndervisningForUndervisningsaktivitetPayloadQueryBuilder : GraphQlQueryBuilder<RegistrerFellesUndervisningForUndervisningsaktivitetPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "undervisningsaktiviteter", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(RegistrerFellesUndervisningForUndervisningsaktivitetErrorQueryBuilder) }
        };

        protected override string TypeName => "RegistrerFellesUndervisningForUndervisningsaktivitetPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public RegistrerFellesUndervisningForUndervisningsaktivitetPayloadQueryBuilder WithUndervisningsaktiviteter(UndervisningsaktivitetQueryBuilder undervisningsaktivitetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisningsaktiviteter", alias, undervisningsaktivitetQueryBuilder, [include, skip]);

        public RegistrerFellesUndervisningForUndervisningsaktivitetPayloadQueryBuilder ExceptUndervisningsaktiviteter() => ExceptField("undervisningsaktiviteter");

        public RegistrerFellesUndervisningForUndervisningsaktivitetPayloadQueryBuilder WithErrors(RegistrerFellesUndervisningForUndervisningsaktivitetErrorQueryBuilder registrerFellesUndervisningForUndervisningsaktivitetErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, registrerFellesUndervisningForUndervisningsaktivitetErrorQueryBuilder, [include, skip]);

        public RegistrerFellesUndervisningForUndervisningsaktivitetPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
