// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class RegistrerGodkjentePolitiattesterPayloadQueryBuilder : GraphQlQueryBuilder<RegistrerGodkjentePolitiattesterPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "godkjentePolitiattester", IsComplex = true, QueryBuilderType = typeof(GodkjentPolitiattestQueryBuilder) },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(RegistrerGodkjentePolitiattesterErrorQueryBuilder) }
        };

        protected override string TypeName => "RegistrerGodkjentePolitiattesterPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public RegistrerGodkjentePolitiattesterPayloadQueryBuilder WithGodkjentePolitiattester(GodkjentPolitiattestQueryBuilder godkjentPolitiattestQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("godkjentePolitiattester", alias, godkjentPolitiattestQueryBuilder, [include, skip]);

        public RegistrerGodkjentePolitiattesterPayloadQueryBuilder ExceptGodkjentePolitiattester() => ExceptField("godkjentePolitiattester");

        public RegistrerGodkjentePolitiattesterPayloadQueryBuilder WithErrors(RegistrerGodkjentePolitiattesterErrorQueryBuilder registrerGodkjentePolitiattesterErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, registrerGodkjentePolitiattesterErrorQueryBuilder, [include, skip]);

        public RegistrerGodkjentePolitiattesterPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
