// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class RegistrerVedtakOmEkstraVurderingsforsokInput : IGraphQlInputObject
    {
        private InputPropertyInfo _id;
        private InputPropertyInfo _innvilget;
        private InputPropertyInfo _merknad;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public QueryBuilderParameter<string> Id
        {
            get => (QueryBuilderParameter<string>)_id.Value;
            set => _id = new() { Name = "id", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("innvilget")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("innvilget")]
        public QueryBuilderParameter<bool?> Innvilget
        {
            get => (QueryBuilderParameter<bool?>)_innvilget.Value;
            set => _innvilget = new() { Name = "innvilget", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("merknad")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("merknad")]
        public QueryBuilderParameter<string> Merknad
        {
            get => (QueryBuilderParameter<string>)_merknad.Value;
            set => _merknad = new() { Name = "merknad", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_id.Name != null) yield return _id;
            if (_innvilget.Name != null) yield return _innvilget;
            if (_merknad.Name != null) yield return _merknad;
        }
    }
}
