// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Resultat")]
    public partial class Resultat : INode, IStudentvurdering
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("karakter")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("karakter")]
        public KarakterResultat Karakter { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vurderingsresultatstatus")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vurderingsresultatstatus")]
        public Vurderingsresultatstatus Vurderingsresultatstatus { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erGyldig")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erGyldig")]
        public bool? ErGyldig { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erKunngjort")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erKunngjort")]
        public bool? ErKunngjort { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tidspunktOpprettet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tidspunktOpprettet")]
        public object TidspunktOpprettet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emne")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emne")]
        public Emne Emne { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("spesialpensumTittel")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("spesialpensumTittel")]
        public SpesialpensumTittel SpesialpensumTittel { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vurderingsenhet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vurderingsenhet")]
        public Vurderingsenhet Vurderingsenhet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("opprinneligLarested")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("opprinneligLarested")]
        public Organisasjon OpprinneligLarested { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("gjeldendeVekting")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("gjeldendeVekting")]
        public VurderingsprotokollGjeldendeVekting GjeldendeVekting { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erOppnadd")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erOppnadd")]
        public bool? ErOppnadd { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vurderingsoppbygningsdelskode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vurderingsoppbygningsdelskode")]
        public string Vurderingsoppbygningsdelskode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("oversattOppgavetittel")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("oversattOppgavetittel")]
        public ResultatOversattOppgavetittel OversattOppgavetittel { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("originalOppgavetittel")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("originalOppgavetittel")]
        public ResultatOriginalOppgavetittel OriginalOppgavetittel { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("larested")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("larested")]
        public Organisasjon Larested { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogram")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogram")]
        public Studieprogram Studieprogram { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kandidatinformasjon")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kandidatinformasjon")]
        public ResultatKandidatinformasjon Kandidatinformasjon { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("student")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("student")]
        public StudentVedLarested Student { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("protokollFoerteEmnesamlinger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("protokollFoerteEmnesamlinger")]
        public ICollection<ProtokollfoertEmnesamling> ProtokollFoerteEmnesamlinger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("oppnaddeKvalifikasjoner")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("oppnaddeKvalifikasjoner")]
        public ICollection<OppnaddKvalifikasjon> OppnaddeKvalifikasjoner { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("children")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("children")]
        public ICollection<Resultat> Children { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("parents")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("parents")]
        public ICollection<Resultat> Parents { get; set; }
    }
}
