// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class ResultatOversattOppgavetittelQueryBuilder : GraphQlQueryBuilder<ResultatOversattOppgavetittelQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "en" }
        };

        protected override string TypeName => "ResultatOversattOppgavetittel";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public ResultatOversattOppgavetittelQueryBuilder WithEn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("en", alias, [include, skip]);

        public ResultatOversattOppgavetittelQueryBuilder ExceptEn() => ExceptField("en");
    }
}
