// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class ResultatOriginalOppgavetittelQueryBuilder : GraphQlQueryBuilder<ResultatOriginalOppgavetittelQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tittel" },
            new() { Name = "sprak", IsComplex = true, QueryBuilderType = typeof(SprakQueryBuilder) }
        };

        protected override string TypeName => "ResultatOriginalOppgavetittel";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public ResultatOriginalOppgavetittelQueryBuilder WithTittel(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tittel", alias, [include, skip]);

        public ResultatOriginalOppgavetittelQueryBuilder ExceptTittel() => ExceptField("tittel");

        public ResultatOriginalOppgavetittelQueryBuilder WithSprak(SprakQueryBuilder sprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("sprak", alias, sprakQueryBuilder, [include, skip]);

        public ResultatOriginalOppgavetittelQueryBuilder ExceptSprak() => ExceptField("sprak");
    }
}
