// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Rom")]
    public partial class Rom : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kode")]
        public string Kode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("navnAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("navnAlleSprak")]
        public RomnavnAlleSprak NavnAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("etasje")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("etasje")]
        public int? Etasje { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("romtype")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("romtype")]
        public Romtype Romtype { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("merknad")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("merknad")]
        public Rommerknad Merknad { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kapasitet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kapasitet")]
        public Romkapasitet Kapasitet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("bygning")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("bygning")]
        public Bygning Bygning { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erAktiv")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erAktiv")]
        public bool? ErAktiv { get; set; }
    }
}
