// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class RomtypeQueryBuilder : GraphQlQueryBuilder<RomtypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kode" },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(RomtypeNavnAlleSprakQueryBuilder) }
        };

        protected override string TypeName => "Romtype";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public RomtypeQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public RomtypeQueryBuilder ExceptId() => ExceptField("id");

        public RomtypeQueryBuilder WithKode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kode", alias, [include, skip]);

        public RomtypeQueryBuilder ExceptKode() => ExceptField("kode");

        public RomtypeQueryBuilder WithNavnAlleSprak(RomtypeNavnAlleSprakQueryBuilder romtypeNavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, romtypeNavnAlleSprakQueryBuilder, [include, skip]);

        public RomtypeQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");
    }
}
