// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class SemesterregistreringStatusBetaltOkQueryBuilder : GraphQlQueryBuilder<SemesterregistreringStatusBetaltOkQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "hendelsestype" },
            new() { Name = "tidspunkt" },
            new() { Name = "student", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedQueryBuilder) },
            new() { Name = "semesterregistrering", IsComplex = true, QueryBuilderType = typeof(SemesterregistreringQueryBuilder) }
        };

        protected override string TypeName => "SemesterregistreringStatusBetaltOk";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public SemesterregistreringStatusBetaltOkQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public SemesterregistreringStatusBetaltOkQueryBuilder ExceptId() => ExceptField("id");

        public SemesterregistreringStatusBetaltOkQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public SemesterregistreringStatusBetaltOkQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public SemesterregistreringStatusBetaltOkQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public SemesterregistreringStatusBetaltOkQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public SemesterregistreringStatusBetaltOkQueryBuilder WithStudent(StudentVedLarestedQueryBuilder studentVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("student", alias, studentVedLarestedQueryBuilder, [include, skip]);

        public SemesterregistreringStatusBetaltOkQueryBuilder ExceptStudent() => ExceptField("student");

        public SemesterregistreringStatusBetaltOkQueryBuilder WithSemesterregistrering(SemesterregistreringQueryBuilder semesterregistreringQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("semesterregistrering", alias, semesterregistreringQueryBuilder, [include, skip]);

        public SemesterregistreringStatusBetaltOkQueryBuilder ExceptSemesterregistrering() => ExceptField("semesterregistrering");
    }
}
