// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class SemesterregistreringshendelseQueryBuilder : GraphQlQueryBuilder<SemesterregistreringshendelseQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "hendelsestype" },
            new() { Name = "tidspunkt" }
        };

        public SemesterregistreringshendelseQueryBuilder() => WithTypeName();

        protected override string TypeName => "Semesterregistreringshendelse";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public SemesterregistreringshendelseQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public SemesterregistreringshendelseQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public SemesterregistreringshendelseQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public SemesterregistreringshendelseQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public SemesterregistreringshendelseQueryBuilder WithSemesterregistreringSlettetFragment(SemesterregistreringSlettetQueryBuilder semesterregistreringSlettetQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(semesterregistreringSlettetQueryBuilder, [include, skip]);

        public SemesterregistreringshendelseQueryBuilder WithSemesterregistreringStatusBetaltOkFragment(SemesterregistreringStatusBetaltOkQueryBuilder semesterregistreringStatusBetaltOkQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(semesterregistreringStatusBetaltOkQueryBuilder, [include, skip]);

        public SemesterregistreringshendelseQueryBuilder WithSemesterregistreringUgyldiggjortFragment(SemesterregistreringUgyldiggjortQueryBuilder semesterregistreringUgyldiggjortQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(semesterregistreringUgyldiggjortQueryBuilder, [include, skip]);

        public SemesterregistreringshendelseQueryBuilder WithStudentSemesterregistrertFragment(StudentSemesterregistrertQueryBuilder studentSemesterregistrertQueryBuilder, IncludeDirective include = null, SkipDirective skip = null) => WithFragment(studentSemesterregistrertQueryBuilder, [include, skip]);
    }
}
