// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class SlettStudentkortPayloadQueryBuilder : GraphQlQueryBuilder<SlettStudentkortPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "ider", IsComplex = true }
        };

        protected override string TypeName => "SlettStudentkortPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public SlettStudentkortPayloadQueryBuilder WithIder(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("ider", alias, [include, skip]);

        public SlettStudentkortPayloadQueryBuilder ExceptIder() => ExceptField("ider");
    }
}
