// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class SlettGodkjentePolitiattesterPayloadQueryBuilder : GraphQlQueryBuilder<SlettGodkjentePolitiattesterPayloadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "ider", IsComplex = true },
            new() { Name = "errors", IsComplex = true, QueryBuilderType = typeof(SlettGodkjentePolitiattesterErrorQueryBuilder) }
        };

        protected override string TypeName => "SlettGodkjentePolitiattesterPayload";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public SlettGodkjentePolitiattesterPayloadQueryBuilder WithIder(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("ider", alias, [include, skip]);

        public SlettGodkjentePolitiattesterPayloadQueryBuilder ExceptIder() => ExceptField("ider");

        public SlettGodkjentePolitiattesterPayloadQueryBuilder WithErrors(SlettGodkjentePolitiattesterErrorQueryBuilder slettGodkjentePolitiattesterErrorQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("errors", alias, slettGodkjentePolitiattesterErrorQueryBuilder, [include, skip]);

        public SlettGodkjentePolitiattesterPayloadQueryBuilder ExceptErrors() => ExceptField("errors");
    }
}
