// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class SlettUndervisningsaktivitetsrollerPayload
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsaktivitetsroller")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsaktivitetsroller")]
        public ICollection<Guid?> Undervisningsaktivitetsroller { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("errors")]
        [JsonConverter(typeof(GraphQlInterfaceJsonConverter))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("errors")]
        public ICollection<ISlettUndervisningsaktivitetrollerError> Errors { get; set; }
    }
}
