// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudienivaintervallQueryBuilder : GraphQlQueryBuilder<StudienivaintervallQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "studienivaintervallkode" }
        };

        protected override string TypeName => "Studienivaintervall";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudienivaintervallQueryBuilder WithStudienivaintervallkode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("studienivaintervallkode", alias, [include, skip]);

        public StudienivaintervallQueryBuilder ExceptStudienivaintervallkode() => ExceptField("studienivaintervallkode");
    }
}
