// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudierettstatusQueryBuilder : GraphQlQueryBuilder<StudierettstatusQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "erAktiv" },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(StudierettstatusnavnAlleSprakQueryBuilder) },
            new() { Name = "beholdVedOvergang" },
            new() { Name = "felleskode" }
        };

        protected override string TypeName => "Studierettstatus";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudierettstatusQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public StudierettstatusQueryBuilder ExceptId() => ExceptField("id");

        public StudierettstatusQueryBuilder WithErAktiv(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erAktiv", alias, [include, skip]);

        public StudierettstatusQueryBuilder ExceptErAktiv() => ExceptField("erAktiv");

        public StudierettstatusQueryBuilder WithNavnAlleSprak(StudierettstatusnavnAlleSprakQueryBuilder studierettstatusnavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, studierettstatusnavnAlleSprakQueryBuilder, [include, skip]);

        public StudierettstatusQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");

        public StudierettstatusQueryBuilder WithBeholdVedOvergang(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("beholdVedOvergang", alias, [include, skip]);

        public StudierettstatusQueryBuilder ExceptBeholdVedOvergang() => ExceptField("beholdVedOvergang");

        public StudierettstatusQueryBuilder WithFelleskode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("felleskode", alias, [include, skip]);

        public StudierettstatusQueryBuilder ExceptFelleskode() => ExceptField("felleskode");
    }
}
