// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieretningForStudieprogramBeskrivelserFilterInput : IGraphQlInputObject
    {
        private InputPropertyInfo _gjelderForTermin;
        private InputPropertyInfo _sprak;
        private InputPropertyInfo _tekstkategorikoder;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("gjelderForTermin")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<StudieretningbeskrivelseTerminInput>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("gjelderForTermin")]
        public QueryBuilderParameter<StudieretningbeskrivelseTerminInput> GjelderForTermin
        {
            get => (QueryBuilderParameter<StudieretningbeskrivelseTerminInput>)_gjelderForTermin.Value;
            set => _gjelderForTermin = new() { Name = "gjelderForTermin", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sprak")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("sprak")]
        public QueryBuilderParameter<string> Sprak
        {
            get => (QueryBuilderParameter<string>)_sprak.Value;
            set => _sprak = new() { Name = "sprak", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tekstkategorikoder")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<ICollection<string>>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tekstkategorikoder")]
        public QueryBuilderParameter<ICollection<string>> Tekstkategorikoder
        {
            get => (QueryBuilderParameter<ICollection<string>>)_tekstkategorikoder.Value;
            set => _tekstkategorikoder = new() { Name = "tekstkategorikoder", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_gjelderForTermin.Name != null) yield return _gjelderForTermin;
            if (_sprak.Name != null) yield return _sprak;
            if (_tekstkategorikoder.Name != null) yield return _tekstkategorikoder;
        }
    }
}
