// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudierettsbegrensningnavnQueryBuilder : GraphQlQueryBuilder<StudierettsbegrensningnavnQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "und" }
        };

        protected override string TypeName => "Studierettsbegrensningnavn";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudierettsbegrensningnavnQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public StudierettsbegrensningnavnQueryBuilder ExceptId() => ExceptField("id");

        public StudierettsbegrensningnavnQueryBuilder WithUnd(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("und", alias, [include, skip]);

        public StudierettsbegrensningnavnQueryBuilder ExceptUnd() => ExceptField("und");
    }
}
