// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieprogramKullConnectionEdgeQueryBuilder : GraphQlQueryBuilder<StudieprogramKullConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(KullQueryBuilder) }
        };

        protected override string TypeName => "StudieprogramKullConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudieprogramKullConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public StudieprogramKullConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public StudieprogramKullConnectionEdgeQueryBuilder WithNode(KullQueryBuilder kullQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, kullQueryBuilder, [include, skip]);

        public StudieprogramKullConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
