// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudentFjernetFraKlasseQueryBuilder : GraphQlQueryBuilder<StudentFjernetFraKlasseQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" },
            new() { Name = "student", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedQueryBuilder) },
            new() { Name = "klassemedlemskapId" },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) }
        };

        protected override string TypeName => "StudentFjernetFraKlasse";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudentFjernetFraKlasseQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public StudentFjernetFraKlasseQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public StudentFjernetFraKlasseQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public StudentFjernetFraKlasseQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public StudentFjernetFraKlasseQueryBuilder WithStudent(StudentVedLarestedQueryBuilder studentVedLarestedQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("student", alias, studentVedLarestedQueryBuilder, [include, skip]);

        public StudentFjernetFraKlasseQueryBuilder ExceptStudent() => ExceptField("student");

        public StudentFjernetFraKlasseQueryBuilder WithKlassemedlemskapId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("klassemedlemskapId", alias, [include, skip]);

        public StudentFjernetFraKlasseQueryBuilder ExceptKlassemedlemskapId() => ExceptField("klassemedlemskapId");

        public StudentFjernetFraKlasseQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public StudentFjernetFraKlasseQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");
    }
}
