// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudentVedLarestedPermisjonerConnectionQueryBuilder : GraphQlQueryBuilder<StudentVedLarestedPermisjonerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedPermisjonerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(PermisjonQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "StudentVedLarestedPermisjonerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudentVedLarestedPermisjonerConnectionQueryBuilder WithEdges(StudentVedLarestedPermisjonerConnectionEdgeQueryBuilder studentVedLarestedPermisjonerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, studentVedLarestedPermisjonerConnectionEdgeQueryBuilder, [include, skip]);

        public StudentVedLarestedPermisjonerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public StudentVedLarestedPermisjonerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public StudentVedLarestedPermisjonerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public StudentVedLarestedPermisjonerConnectionQueryBuilder WithNodes(PermisjonQueryBuilder permisjonQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, permisjonQueryBuilder, [include, skip]);

        public StudentVedLarestedPermisjonerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public StudentVedLarestedPermisjonerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public StudentVedLarestedPermisjonerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
