// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudentVedLarestedResultaterV2ConnectionQueryBuilder : GraphQlQueryBuilder<StudentVedLarestedResultaterV2ConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedResultaterV2ConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(ResultatQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "StudentVedLarestedResultaterV2Connection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder WithEdges(StudentVedLarestedResultaterV2ConnectionEdgeQueryBuilder studentVedLarestedResultaterV2ConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, studentVedLarestedResultaterV2ConnectionEdgeQueryBuilder, [include, skip]);

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder WithNodes(ResultatQueryBuilder resultatQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, resultatQueryBuilder, [include, skip]);

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public StudentVedLarestedResultaterV2ConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
