// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieretningForStudieprogramQueryBuilder : GraphQlQueryBuilder<StudieretningForStudieprogramQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "studieretning", IsComplex = true, QueryBuilderType = typeof(StudieretningQueryBuilder) },
            new() { Name = "erAktiv" },
            new() { Name = "tilbysIPeriode", IsComplex = true, QueryBuilderType = typeof(StudieretningForStudieprogramTerminPeriodeQueryBuilder) },
            new() { Name = "beskrivelser", IsComplex = true, QueryBuilderType = typeof(StudieretningForStudieprogramBeskrivelserConnectionQueryBuilder) }
        };

        protected override string TypeName => "StudieretningForStudieprogram";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudieretningForStudieprogramQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public StudieretningForStudieprogramQueryBuilder ExceptId() => ExceptField("id");

        public StudieretningForStudieprogramQueryBuilder WithStudieretning(StudieretningQueryBuilder studieretningQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("studieretning", alias, studieretningQueryBuilder, [include, skip]);

        public StudieretningForStudieprogramQueryBuilder ExceptStudieretning() => ExceptField("studieretning");

        public StudieretningForStudieprogramQueryBuilder WithErAktiv(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erAktiv", alias, [include, skip]);

        public StudieretningForStudieprogramQueryBuilder ExceptErAktiv() => ExceptField("erAktiv");

        public StudieretningForStudieprogramQueryBuilder WithTilbysIPeriode(StudieretningForStudieprogramTerminPeriodeQueryBuilder studieretningForStudieprogramTerminPeriodeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("tilbysIPeriode", alias, studieretningForStudieprogramTerminPeriodeQueryBuilder, [include, skip]);

        public StudieretningForStudieprogramQueryBuilder ExceptTilbysIPeriode() => ExceptField("tilbysIPeriode");

        public StudieretningForStudieprogramQueryBuilder WithBeskrivelser(StudieretningForStudieprogramBeskrivelserConnectionQueryBuilder studieretningForStudieprogramBeskrivelserConnectionQueryBuilder, QueryBuilderParameter<StudieretningForStudieprogramBeskrivelserFilterInput> filter = null, QueryBuilderParameter<int?> first = null, QueryBuilderParameter<string> after = null, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            var args = new List<QueryBuilderArgumentInfo>();
            if (filter != null)
                args.Add(new() { ArgumentName = "filter", ArgumentValue = filter} );

            if (first != null)
                args.Add(new() { ArgumentName = "first", ArgumentValue = first} );

            if (after != null)
                args.Add(new() { ArgumentName = "after", ArgumentValue = after} );

            return WithObjectField("beskrivelser", alias, studieretningForStudieprogramBeskrivelserConnectionQueryBuilder, [include, skip], args);
        }

        public StudieretningForStudieprogramQueryBuilder ExceptBeskrivelser() => ExceptField("beskrivelser");
    }
}
