// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder : GraphQlQueryBuilder<StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(FsOpptaksterminQueryBuilder) }
        };

        protected override string TypeName => "StudieprogramFsOpptaksterminerConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder WithNode(FsOpptaksterminQueryBuilder fsOpptaksterminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, fsOpptaksterminQueryBuilder, [include, skip]);

        public StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
