// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudentVedLarestedFakturaerConnectionQueryBuilder : GraphQlQueryBuilder<StudentVedLarestedFakturaerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(StudentVedLarestedFakturaerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(FakturaQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "StudentVedLarestedFakturaerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudentVedLarestedFakturaerConnectionQueryBuilder WithEdges(StudentVedLarestedFakturaerConnectionEdgeQueryBuilder studentVedLarestedFakturaerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, studentVedLarestedFakturaerConnectionEdgeQueryBuilder, [include, skip]);

        public StudentVedLarestedFakturaerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public StudentVedLarestedFakturaerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public StudentVedLarestedFakturaerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public StudentVedLarestedFakturaerConnectionQueryBuilder WithNodes(FakturaQueryBuilder fakturaQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, fakturaQueryBuilder, [include, skip]);

        public StudentVedLarestedFakturaerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public StudentVedLarestedFakturaerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public StudentVedLarestedFakturaerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
