// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudierettperiodeQueryBuilder : GraphQlQueryBuilder<StudierettperiodeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "fraDato" },
            new() { Name = "tilDato" }
        };

        protected override string TypeName => "Studierettperiode";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudierettperiodeQueryBuilder WithFraDato(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("fraDato", alias, [include, skip]);

        public StudierettperiodeQueryBuilder ExceptFraDato() => ExceptField("fraDato");

        public StudierettperiodeQueryBuilder WithTilDato(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tilDato", alias, [include, skip]);

        public StudierettperiodeQueryBuilder ExceptTilDato() => ExceptField("tilDato");
    }
}
