// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Studieprogram")]
    public partial class Studieprogram : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kode")]
        public string Kode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("navnAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("navnAlleSprak")]
        public StudieprogramnavnAlleSprak NavnAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erAktiv")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erAktiv")]
        public bool? ErAktiv { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("beskrivelsesavsnitt")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("beskrivelsesavsnitt")]
        public StudieprogramBeskrivelsesavsnittConnection Beskrivelsesavsnitt { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsorganisering")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsorganisering")]
        public Undervisningsorganisering Undervisningsorganisering { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("godkjenning")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("godkjenning")]
        public StudieprogramGodkjenning Godkjenning { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vekting")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vekting")]
        public StudieprogramVekting Vekting { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("prosentHeltid")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("prosentHeltid")]
        public int? ProsentHeltid { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("varighet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("varighet")]
        public Studieprogramvarighet Varighet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieoppbygninger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieoppbygninger")]
        public ICollection<StudieoppbygningForKull> Studieoppbygninger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("nusKode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("nusKode")]
        public string NusKode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieniva")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieniva")]
        public Studieniva Studieniva { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("personroller")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("personroller")]
        public ICollection<Studieprogramrolle> Personroller { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieretninger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieretninger")]
        public StudieprogramStudieretningerConnection Studieretninger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("campuser")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("campuser")]
        public StudieprogramCampuserConnection Campuser { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieansvarligOrganisasjonsenhet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieansvarligOrganisasjonsenhet")]
        public Organisasjonsenhet StudieansvarligOrganisasjonsenhet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kull")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kull")]
        public StudieprogramKullConnection Kull { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("skalEksporteresTilLms")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("skalEksporteresTilLms")]
        public bool? SkalEksporteresTilLms { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("lmsRomkode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("lmsRomkode")]
        public string LmsRomkode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("skalPubliseres")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("skalPubliseres")]
        public bool? SkalPubliseres { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("urlAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("urlAlleSprak")]
        public StudieprogramUrlAlleSprak UrlAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utdanningsomrade")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("utdanningsomrade")]
        public Utdanningsomrade Utdanningsomrade { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("sprak")]
        public ICollection<StudieprogramSprak> Sprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("forerTilKvalifikasjon")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("forerTilKvalifikasjon")]
        public Kvalifikasjon ForerTilKvalifikasjon { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fsOpptaksterminer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fsOpptaksterminer")]
        public StudieprogramFsOpptaksterminerConnection FsOpptaksterminer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("navnAlleSprakHistorikk")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("navnAlleSprakHistorikk")]
        public ICollection<StudieprogramNavnehistorikk> NavnAlleSprakHistorikk { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("prosentEgenfinansiering")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("prosentEgenfinansiering")]
        public int? ProsentEgenfinansiering { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("prosentPraksis")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("prosentPraksis")]
        public int? ProsentPraksis { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studenterSkalHaUtdanningsplan")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studenterSkalHaUtdanningsplan")]
        public bool? StudenterSkalHaUtdanningsplan { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieprogramkategori")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieprogramkategori")]
        public Studieprogramkategori Studieprogramkategori { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sisteOpptakstermin")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("sisteOpptakstermin")]
        public Termin SisteOpptakstermin { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("finansieringstype")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("finansieringstype")]
        public Finansieringstype Finansieringstype { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("subjectareaForErasmus")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("subjectareaForErasmus")]
        public SubjectArea SubjectareaForErasmus { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("videreutdanningsstatus")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("videreutdanningsstatus")]
        public Videreutdanningsstatus Videreutdanningsstatus { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sistEndretDato")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("sistEndretDato")]
        public object SistEndretDato { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emneKoblinger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emneKoblinger")]
        public ICollection<StudieprogramEmnekobling> EmneKoblinger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("rapporteringTilLanekassen")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("rapporteringTilLanekassen")]
        public ICollection<RapporteringTilLanekassen> RapporteringTilLanekassen { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("publiseringsklartITerminer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("publiseringsklartITerminer")]
        public ICollection<PubliseringsklartStudieprogramForTermin> PubliseringsklartITerminer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("nusklassifikasjon")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("nusklassifikasjon")]
        public Nusklassifikasjon Nusklassifikasjon { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("programStudieretter")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("programStudieretter")]
        public ICollection<ProgramStudierett> ProgramStudieretter { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utvekslingsavtalekoblinger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("utvekslingsavtalekoblinger")]
        public ICollection<StudieprogramUtvekslingsavtaleKobling> Utvekslingsavtalekoblinger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studienivaintervallkode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studienivaintervallkode")]
        public StudienivaIntervallKode? Studienivaintervallkode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vitnemalsnavnAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vitnemalsnavnAlleSprak")]
        public StudieprogramVitnemalsnavnAlleSprak VitnemalsnavnAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fagkoblinger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fagkoblinger")]
        public StudieprogramFagkoblinger Fagkoblinger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("datoOpprettet")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("datoOpprettet")]
        public object DatoOpprettet { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utdanningsregisterSpesifikasjonsId")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("utdanningsregisterSpesifikasjonsId")]
        public string UtdanningsregisterSpesifikasjonsId { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utdanningsregisterMulighetsId")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("utdanningsregisterMulighetsId")]
        public string UtdanningsregisterMulighetsId { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erGrunnstudium")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erGrunnstudium")]
        public bool? ErGrunnstudium { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("tilbysIPeriode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("tilbysIPeriode")]
        public StudieprogramTilbudsPeriode TilbysIPeriode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("skalEksporteresTilUtdanningsregisteret")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("skalEksporteresTilUtdanningsregisteret")]
        public bool? SkalEksporteresTilUtdanningsregisteret { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("samarbeidsinstitusjoner")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("samarbeidsinstitusjoner")]
        public ICollection<StudieprogramSamarbeid> Samarbeidsinstitusjoner { get; set; }
    }
}
