// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieoppbygningsdelFrieEmnevalg
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("harFrieEmnevalg")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("harFrieEmnevalg")]
        public bool? HarFrieEmnevalg { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("begrensninger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("begrensninger")]
        public ICollection<BegrensningForEmnevalgIStudieoppbygningsdel> Begrensninger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("beregnStudieoppbygningsdelVedValgAvFrieEmner")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("beregnStudieoppbygningsdelVedValgAvFrieEmner")]
        public bool? BeregnStudieoppbygningsdelVedValgAvFrieEmner { get; set; }
    }
}
