// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudietilpasningstypeQueryBuilder : GraphQlQueryBuilder<StudietilpasningstypeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "navn", IsComplex = true, QueryBuilderType = typeof(StudietilpasningstypenavnQueryBuilder) },
            new() { Name = "gjelderUndervisning" },
            new() { Name = "gjelderPraksis" },
            new() { Name = "gjelderEksamen" },
            new() { Name = "ekstraEksamenstid" },
            new() { Name = "gyldighetsperiode", IsComplex = true, QueryBuilderType = typeof(StudietilpasningstypeGyldighetsperiodeQueryBuilder) },
            new() { Name = "merknad", IsComplex = true, QueryBuilderType = typeof(StudietilpasningstypemerknadQueryBuilder) },
            new() { Name = "aktiv" },
            new() { Name = "felleskode" }
        };

        protected override string TypeName => "Studietilpasningstype";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudietilpasningstypeQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptId() => ExceptField("id");

        public StudietilpasningstypeQueryBuilder WithNavn(StudietilpasningstypenavnQueryBuilder studietilpasningstypenavnQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navn", alias, studietilpasningstypenavnQueryBuilder, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptNavn() => ExceptField("navn");

        public StudietilpasningstypeQueryBuilder WithGjelderUndervisning(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("gjelderUndervisning", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptGjelderUndervisning() => ExceptField("gjelderUndervisning");

        public StudietilpasningstypeQueryBuilder WithGjelderPraksis(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("gjelderPraksis", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptGjelderPraksis() => ExceptField("gjelderPraksis");

        public StudietilpasningstypeQueryBuilder WithGjelderEksamen(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("gjelderEksamen", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptGjelderEksamen() => ExceptField("gjelderEksamen");

        public StudietilpasningstypeQueryBuilder WithEkstraEksamenstid(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("ekstraEksamenstid", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptEkstraEksamenstid() => ExceptField("ekstraEksamenstid");

        public StudietilpasningstypeQueryBuilder WithGyldighetsperiode(StudietilpasningstypeGyldighetsperiodeQueryBuilder studietilpasningstypeGyldighetsperiodeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("gyldighetsperiode", alias, studietilpasningstypeGyldighetsperiodeQueryBuilder, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptGyldighetsperiode() => ExceptField("gyldighetsperiode");

        public StudietilpasningstypeQueryBuilder WithMerknad(StudietilpasningstypemerknadQueryBuilder studietilpasningstypemerknadQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("merknad", alias, studietilpasningstypemerknadQueryBuilder, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptMerknad() => ExceptField("merknad");

        public StudietilpasningstypeQueryBuilder WithAktiv(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("aktiv", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptAktiv() => ExceptField("aktiv");

        public StudietilpasningstypeQueryBuilder WithFelleskode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("felleskode", alias, [include, skip]);

        public StudietilpasningstypeQueryBuilder ExceptFelleskode() => ExceptField("felleskode");
    }
}
