// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieprogramKullConnectionQueryBuilder : GraphQlQueryBuilder<StudieprogramKullConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(StudieprogramKullConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(KullQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "StudieprogramKullConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudieprogramKullConnectionQueryBuilder WithEdges(StudieprogramKullConnectionEdgeQueryBuilder studieprogramKullConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, studieprogramKullConnectionEdgeQueryBuilder, [include, skip]);

        public StudieprogramKullConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public StudieprogramKullConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public StudieprogramKullConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public StudieprogramKullConnectionQueryBuilder WithNodes(KullQueryBuilder kullQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, kullQueryBuilder, [include, skip]);

        public StudieprogramKullConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public StudieprogramKullConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public StudieprogramKullConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
