// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudierettTerminperiodeQueryBuilder : GraphQlQueryBuilder<StudierettTerminperiodeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "fraTermin", IsComplex = true, QueryBuilderType = typeof(TerminQueryBuilder) },
            new() { Name = "tilTermin", IsComplex = true, QueryBuilderType = typeof(TerminQueryBuilder) }
        };

        protected override string TypeName => "StudierettTerminperiode";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudierettTerminperiodeQueryBuilder WithFraTermin(TerminQueryBuilder terminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("fraTermin", alias, terminQueryBuilder, [include, skip]);

        public StudierettTerminperiodeQueryBuilder ExceptFraTermin() => ExceptField("fraTermin");

        public StudierettTerminperiodeQueryBuilder WithTilTermin(TerminQueryBuilder terminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("tilTermin", alias, terminQueryBuilder, [include, skip]);

        public StudierettTerminperiodeQueryBuilder ExceptTilTermin() => ExceptField("tilTermin");
    }
}
