// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudentManglerGskOgStudentgrlErrorQueryBuilder : GraphQlQueryBuilder<StudentManglerGskOgStudentgrlErrorQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "path", IsComplex = true },
            new() { Name = "message" }
        };

        protected override string TypeName => "StudentManglerGskOgStudentgrlError";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudentManglerGskOgStudentgrlErrorQueryBuilder WithPath(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("path", alias, [include, skip]);

        public StudentManglerGskOgStudentgrlErrorQueryBuilder ExceptPath() => ExceptField("path");

        public StudentManglerGskOgStudentgrlErrorQueryBuilder WithMessage(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("message", alias, [include, skip]);

        public StudentManglerGskOgStudentgrlErrorQueryBuilder ExceptMessage() => ExceptField("message");
    }
}
