// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieprogramFsOpptaksterminerConnectionQueryBuilder : GraphQlQueryBuilder<StudieprogramFsOpptaksterminerConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(FsOpptaksterminQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "StudieprogramFsOpptaksterminerConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder WithEdges(StudieprogramFsOpptaksterminerConnectionEdgeQueryBuilder studieprogramFsOpptaksterminerConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, studieprogramFsOpptaksterminerConnectionEdgeQueryBuilder, [include, skip]);

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder WithNodes(FsOpptaksterminQueryBuilder fsOpptaksterminQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, fsOpptaksterminQueryBuilder, [include, skip]);

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public StudieprogramFsOpptaksterminerConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
