// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public enum Studenthendelsestype
    {
        [EnumMember(Value = "DODSFALL")] Dodsfall,
        [EnumMember(Value = "DODSFALL_ANNULLERT")] DodsfallAnnullert,
        [EnumMember(Value = "ENDRET_BIBLIOTEK")] EndretBibliotek,
        [EnumMember(Value = "ENDRET_FEIDE_BRUKER")] EndretFeideBruker,
        [EnumMember(Value = "ENDRET_FOLKEREGISTRERT_ADRESSE")] EndretFolkeregistrertAdresse,
        [EnumMember(Value = "ENDRET_LANETAKER_ID")] EndretLanetakerId,
        [EnumMember(Value = "ENDRET_POSTADRESSE")] EndretPostadresse,
        [EnumMember(Value = "ENDRET_MOBILNUMMER")] EndretMobilnummer,
        [EnumMember(Value = "ENDRET_MALFORM")] EndretMalform,
        [EnumMember(Value = "ENDRET_NAVN")] EndretNavn,
        [EnumMember(Value = "ENDRET_STUDENTNUMMER")] EndretStudentnummer,
        [EnumMember(Value = "SEMESTERREGISTRERT")] Semesterregistrert,
        [EnumMember(Value = "SLUTTET_PA_STUDIEPROGRAM")] SluttetPaStudieprogram,
        [EnumMember(Value = "STARTET_PA_STUDIEPROGRAM")] StartetPaStudieprogram,
        [EnumMember(Value = "STUDENTKORT_UTSTEDT")] StudentkortUtstedt,
        [EnumMember(Value = "STUDENTKORT_UTGATT")] StudentkortUtgatt,
        [EnumMember(Value = "STUDENTKORT_UGYLDIGGJORT")] StudentkortUgyldiggjort,
        [EnumMember(Value = "STUDENTKORT_GYLDIGGJORT")] StudentkortGyldiggjort,
        [EnumMember(Value = "STUDENTKORT_FORLENGET")] StudentkortForlenget,
        [EnumMember(Value = "STUDIERETT_FORLENGET")] StudierettForlenget,
        [EnumMember(Value = "VURDERINGSMELDT")] Vurderingsmeldt,
        [EnumMember(Value = "VURDERINGSMELDING_SLETTET")] VurderingsmeldingSlettet,
        [EnumMember(Value = "ENDRET_EPOSTADRESSE")] EndretEpostadresse,
        [EnumMember(Value = "ENDRET_FODSELSDATO")] EndretFodselsdato,
        [EnumMember(Value = "SEMESTERREGISTRERING_UGYLDIGGJORT")] SemesterregistreringUgyldiggjort,
        [EnumMember(Value = "STUDENT_PLASSERT_I_KLASSE")] StudentPlassertIKlasse,
        [EnumMember(Value = "STUDENT_FJERNET_FRA_KLASSE")] StudentFjernetFraKlasse,
        [EnumMember(Value = "KLASSEMEDLEMSKAP_DEAKTIVERT")] KlassemedlemskapDeaktivert,
        [EnumMember(Value = "KLASSEMEDLEMSKAP_AKTIVERT")] KlassemedlemskapAktivert,
        [EnumMember(Value = "STUDENT_ENDRET_KULL")] StudentEndretKull,
        [EnumMember(Value = "SEMESTERREGISTRERING_SLETTET")] SemesterregistreringSlettet,
        [EnumMember(Value = "SEMESTERREGISTRERING_STATUS_BET_OK")] SemesterregistreringStatusBetOk
    }
}
