// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class StudieoppbygningsdelIHierarkiQueryBuilder : GraphQlQueryBuilder<StudieoppbygningsdelIHierarkiQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "parent", IsComplex = true, QueryBuilderType = typeof(StudieoppbygningsdelIHierarkiQueryBuilder) },
            new() { Name = "studieoppbygningsdel", IsComplex = true, QueryBuilderType = typeof(StudieoppbygningsdelQueryBuilder) },
            new() { Name = "children", IsComplex = true, QueryBuilderType = typeof(StudieoppbygningsdelIHierarkiQueryBuilder) },
            new() { Name = "rekkefolgenummer" },
            new() { Name = "terminNummerRelativStart" },
            new() { Name = "terminNummerValgbarFra" },
            new() { Name = "lukket" },
            new() { Name = "timeplanSkalGenereres" },
            new() { Name = "kullterminer", IsComplex = true, QueryBuilderType = typeof(StudieoppbyggingIStudieoppbygningKullperiodeQueryBuilder) }
        };

        protected override string TypeName => "StudieoppbygningsdelIHierarki";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public StudieoppbygningsdelIHierarkiQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptId() => ExceptField("id");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithParent(StudieoppbygningsdelIHierarkiQueryBuilder studieoppbygningsdelIHierarkiQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("parent", alias, studieoppbygningsdelIHierarkiQueryBuilder, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptParent() => ExceptField("parent");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithStudieoppbygningsdel(StudieoppbygningsdelQueryBuilder studieoppbygningsdelQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("studieoppbygningsdel", alias, studieoppbygningsdelQueryBuilder, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptStudieoppbygningsdel() => ExceptField("studieoppbygningsdel");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithChildren(StudieoppbygningsdelIHierarkiQueryBuilder studieoppbygningsdelIHierarkiQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("children", alias, studieoppbygningsdelIHierarkiQueryBuilder, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptChildren() => ExceptField("children");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithRekkefolgenummer(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("rekkefolgenummer", alias, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptRekkefolgenummer() => ExceptField("rekkefolgenummer");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithTerminNummerRelativStart(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("terminNummerRelativStart", alias, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptTerminNummerRelativStart() => ExceptField("terminNummerRelativStart");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithTerminNummerValgbarFra(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("terminNummerValgbarFra", alias, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptTerminNummerValgbarFra() => ExceptField("terminNummerValgbarFra");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithLukket(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("lukket", alias, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptLukket() => ExceptField("lukket");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithTimeplanSkalGenereres(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("timeplanSkalGenereres", alias, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptTimeplanSkalGenereres() => ExceptField("timeplanSkalGenereres");

        public StudieoppbygningsdelIHierarkiQueryBuilder WithKullterminer(StudieoppbyggingIStudieoppbygningKullperiodeQueryBuilder studieoppbyggingIStudieoppbygningKullperiodeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("kullterminer", alias, studieoppbyggingIStudieoppbygningKullperiodeQueryBuilder, [include, skip]);

        public StudieoppbygningsdelIHierarkiQueryBuilder ExceptKullterminer() => ExceptField("kullterminer");
    }
}
