// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class SvarPaTilbudQueryBuilder : GraphQlQueryBuilder<SvarPaTilbudQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kode" },
            new() { Name = "navn", IsComplex = true, QueryBuilderType = typeof(SvarPaTilbudNavnAlleSprakQueryBuilder) }
        };

        protected override string TypeName => "SvarPaTilbud";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public SvarPaTilbudQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public SvarPaTilbudQueryBuilder ExceptId() => ExceptField("id");

        public SvarPaTilbudQueryBuilder WithKode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kode", alias, [include, skip]);

        public SvarPaTilbudQueryBuilder ExceptKode() => ExceptField("kode");

        public SvarPaTilbudQueryBuilder WithNavn(SvarPaTilbudNavnAlleSprakQueryBuilder svarPaTilbudNavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navn", alias, svarPaTilbudNavnAlleSprakQueryBuilder, [include, skip]);

        public SvarPaTilbudQueryBuilder ExceptNavn() => ExceptField("navn");
    }
}
