// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class TerminkodeInput : IGraphQlInputObject
    {
        private InputPropertyInfo _arstall;
        private InputPropertyInfo _terminkode;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("arstall")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("arstall")]
        public QueryBuilderParameter<int?> Arstall
        {
            get => (QueryBuilderParameter<int?>)_arstall.Value;
            set => _arstall = new() { Name = "arstall", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminkode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminkode")]
        public QueryBuilderParameter<string> Terminkode
        {
            get => (QueryBuilderParameter<string>)_terminkode.Value;
            set => _terminkode = new() { Name = "terminkode", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_arstall.Name != null) yield return _arstall;
            if (_terminkode.Name != null) yield return _terminkode;
        }
    }
}
