// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class TidligerePersonNavnQueryBuilder : GraphQlQueryBuilder<TidligerePersonNavnQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "endret" },
            new() { Name = "fornavn" },
            new() { Name = "etternavn" },
            new() { Name = "grunnlag", IsComplex = true, QueryBuilderType = typeof(NavneendringsgrunnlagQueryBuilder) }
        };

        protected override string TypeName => "TidligerePersonNavn";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public TidligerePersonNavnQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public TidligerePersonNavnQueryBuilder ExceptId() => ExceptField("id");

        public TidligerePersonNavnQueryBuilder WithEndret(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("endret", alias, [include, skip]);

        public TidligerePersonNavnQueryBuilder ExceptEndret() => ExceptField("endret");

        public TidligerePersonNavnQueryBuilder WithFornavn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("fornavn", alias, [include, skip]);

        public TidligerePersonNavnQueryBuilder ExceptFornavn() => ExceptField("fornavn");

        public TidligerePersonNavnQueryBuilder WithEtternavn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("etternavn", alias, [include, skip]);

        public TidligerePersonNavnQueryBuilder ExceptEtternavn() => ExceptField("etternavn");

        public TidligerePersonNavnQueryBuilder WithGrunnlag(NavneendringsgrunnlagQueryBuilder navneendringsgrunnlagQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("grunnlag", alias, navneendringsgrunnlagQueryBuilder, [include, skip]);

        public TidligerePersonNavnQueryBuilder ExceptGrunnlag() => ExceptField("grunnlag");
    }
}
