// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class TilbudstatusQueryBuilder : GraphQlQueryBuilder<TilbudstatusQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kode" },
            new() { Name = "navn", IsComplex = true, QueryBuilderType = typeof(TilbudstatusnavnAlleSprakQueryBuilder) }
        };

        protected override string TypeName => "Tilbudstatus";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public TilbudstatusQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public TilbudstatusQueryBuilder ExceptId() => ExceptField("id");

        public TilbudstatusQueryBuilder WithKode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kode", alias, [include, skip]);

        public TilbudstatusQueryBuilder ExceptKode() => ExceptField("kode");

        public TilbudstatusQueryBuilder WithNavn(TilbudstatusnavnAlleSprakQueryBuilder tilbudstatusnavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navn", alias, tilbudstatusnavnAlleSprakQueryBuilder, [include, skip]);

        public TilbudstatusQueryBuilder ExceptNavn() => ExceptField("navn");
    }
}
