// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class TimeplanrolleBleAktivQueryBuilder : GraphQlQueryBuilder<TimeplanrolleBleAktivQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "timeplanrolle", IsComplex = true, QueryBuilderType = typeof(TimeplanrolleQueryBuilder) },
            new() { Name = "personProfil", IsComplex = true, QueryBuilderType = typeof(PersonProfilQueryBuilder) },
            new() { Name = "tidspunkt" },
            new() { Name = "hendelsestype" }
        };

        protected override string TypeName => "TimeplanrolleBleAktiv";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public TimeplanrolleBleAktivQueryBuilder WithTimeplanrolle(TimeplanrolleQueryBuilder timeplanrolleQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("timeplanrolle", alias, timeplanrolleQueryBuilder, [include, skip]);

        public TimeplanrolleBleAktivQueryBuilder ExceptTimeplanrolle() => ExceptField("timeplanrolle");

        public TimeplanrolleBleAktivQueryBuilder WithPersonProfil(PersonProfilQueryBuilder personProfilQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("personProfil", alias, personProfilQueryBuilder, [include, skip]);

        public TimeplanrolleBleAktivQueryBuilder ExceptPersonProfil() => ExceptField("personProfil");

        public TimeplanrolleBleAktivQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public TimeplanrolleBleAktivQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public TimeplanrolleBleAktivQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public TimeplanrolleBleAktivQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");
    }
}
