// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class UndervisningstilpasningsmerknadQueryBuilder : GraphQlQueryBuilder<UndervisningstilpasningsmerknadQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "und" }
        };

        protected override string TypeName => "Undervisningstilpasningsmerknad";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public UndervisningstilpasningsmerknadQueryBuilder WithUnd(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("und", alias, [include, skip]);

        public UndervisningstilpasningsmerknadQueryBuilder ExceptUnd() => ExceptField("und");
    }
}
