// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class UndervisningsaktivitetQueryBuilder : GraphQlQueryBuilder<UndervisningsaktivitetQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "kode" },
            new() { Name = "parent", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetQueryBuilder) },
            new() { Name = "undervisningsenhet", IsComplex = true, QueryBuilderType = typeof(UndervisningsenhetQueryBuilder) },
            new() { Name = "partinummer" },
            new() { Name = "lmsRomkode" },
            new() { Name = "skalEksporteresTilLms" },
            new() { Name = "navnAlleSprak", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetnavnAlleSprakQueryBuilder) },
            new() { Name = "undervisesVedOrganisasjonsenhet", IsComplex = true, QueryBuilderType = typeof(OrganisasjonsenhetQueryBuilder) },
            new() { Name = "personroller", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetsrolleQueryBuilder) },
            new() { Name = "underliggendeAktiviteterErEkvivalente" },
            new() { Name = "erLukket" },
            new() { Name = "disiplin", IsComplex = true, QueryBuilderType = typeof(UndervisningsdisiplinQueryBuilder) },
            new() { Name = "undervisningsform", IsComplex = true, QueryBuilderType = typeof(UndervisningsformQueryBuilder) },
            new() { Name = "sekvensnummer" },
            new() { Name = "undervisningskommentarAlleSprak", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetUndervisningskommentarAlleSprakQueryBuilder) },
            new() { Name = "timerPerUke" },
            new() { Name = "undervisesVedOrganisasjon", IsComplex = true, QueryBuilderType = typeof(OrganisasjonQueryBuilder) },
            new() { Name = "antallPlasser" },
            new() { Name = "erFellesaktivitet" },
            new() { Name = "campus", IsComplex = true, QueryBuilderType = typeof(CampusQueryBuilder) },
            new() { Name = "skalEksporteresTilTimeplansystem" },
            new() { Name = "timeplaner", IsComplex = true, QueryBuilderType = typeof(UndervisningsaktivitetTimeplanerConnectionQueryBuilder) }
        };

        protected override string TypeName => "Undervisningsaktivitet";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public UndervisningsaktivitetQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptId() => ExceptField("id");

        public UndervisningsaktivitetQueryBuilder WithKode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("kode", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptKode() => ExceptField("kode");

        public UndervisningsaktivitetQueryBuilder WithParent(UndervisningsaktivitetQueryBuilder undervisningsaktivitetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("parent", alias, undervisningsaktivitetQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptParent() => ExceptField("parent");

        public UndervisningsaktivitetQueryBuilder WithUndervisningsenhet(UndervisningsenhetQueryBuilder undervisningsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisningsenhet", alias, undervisningsenhetQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptUndervisningsenhet() => ExceptField("undervisningsenhet");

        public UndervisningsaktivitetQueryBuilder WithPartinummer(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("partinummer", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptPartinummer() => ExceptField("partinummer");

        public UndervisningsaktivitetQueryBuilder WithLmsRomkode(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("lmsRomkode", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptLmsRomkode() => ExceptField("lmsRomkode");

        public UndervisningsaktivitetQueryBuilder WithSkalEksporteresTilLms(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("skalEksporteresTilLms", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptSkalEksporteresTilLms() => ExceptField("skalEksporteresTilLms");

        public UndervisningsaktivitetQueryBuilder WithNavnAlleSprak(UndervisningsaktivitetnavnAlleSprakQueryBuilder undervisningsaktivitetnavnAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("navnAlleSprak", alias, undervisningsaktivitetnavnAlleSprakQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptNavnAlleSprak() => ExceptField("navnAlleSprak");

        public UndervisningsaktivitetQueryBuilder WithUndervisesVedOrganisasjonsenhet(OrganisasjonsenhetQueryBuilder organisasjonsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisesVedOrganisasjonsenhet", alias, organisasjonsenhetQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptUndervisesVedOrganisasjonsenhet() => ExceptField("undervisesVedOrganisasjonsenhet");

        public UndervisningsaktivitetQueryBuilder WithPersonroller(UndervisningsaktivitetsrolleQueryBuilder undervisningsaktivitetsrolleQueryBuilder, QueryBuilderParameter<UndervisningsaktivitetPersonrollerFilter> filter = null, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            var args = new List<QueryBuilderArgumentInfo>();
            if (filter != null)
                args.Add(new() { ArgumentName = "filter", ArgumentValue = filter} );

            return WithObjectField("personroller", alias, undervisningsaktivitetsrolleQueryBuilder, [include, skip], args);
        }

        public UndervisningsaktivitetQueryBuilder ExceptPersonroller() => ExceptField("personroller");

        public UndervisningsaktivitetQueryBuilder WithUnderliggendeAktiviteterErEkvivalente(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("underliggendeAktiviteterErEkvivalente", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptUnderliggendeAktiviteterErEkvivalente() => ExceptField("underliggendeAktiviteterErEkvivalente");

        public UndervisningsaktivitetQueryBuilder WithErLukket(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erLukket", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptErLukket() => ExceptField("erLukket");

        public UndervisningsaktivitetQueryBuilder WithDisiplin(UndervisningsdisiplinQueryBuilder undervisningsdisiplinQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("disiplin", alias, undervisningsdisiplinQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptDisiplin() => ExceptField("disiplin");

        public UndervisningsaktivitetQueryBuilder WithUndervisningsform(UndervisningsformQueryBuilder undervisningsformQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisningsform", alias, undervisningsformQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptUndervisningsform() => ExceptField("undervisningsform");

        public UndervisningsaktivitetQueryBuilder WithSekvensnummer(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("sekvensnummer", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptSekvensnummer() => ExceptField("sekvensnummer");

        public UndervisningsaktivitetQueryBuilder WithUndervisningskommentarAlleSprak(UndervisningsaktivitetUndervisningskommentarAlleSprakQueryBuilder undervisningsaktivitetUndervisningskommentarAlleSprakQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisningskommentarAlleSprak", alias, undervisningsaktivitetUndervisningskommentarAlleSprakQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptUndervisningskommentarAlleSprak() => ExceptField("undervisningskommentarAlleSprak");

        public UndervisningsaktivitetQueryBuilder WithTimerPerUke(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("timerPerUke", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptTimerPerUke() => ExceptField("timerPerUke");

        public UndervisningsaktivitetQueryBuilder WithUndervisesVedOrganisasjon(OrganisasjonQueryBuilder organisasjonQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisesVedOrganisasjon", alias, organisasjonQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptUndervisesVedOrganisasjon() => ExceptField("undervisesVedOrganisasjon");

        public UndervisningsaktivitetQueryBuilder WithAntallPlasser(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("antallPlasser", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptAntallPlasser() => ExceptField("antallPlasser");

        public UndervisningsaktivitetQueryBuilder WithErFellesaktivitet(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("erFellesaktivitet", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptErFellesaktivitet() => ExceptField("erFellesaktivitet");

        public UndervisningsaktivitetQueryBuilder WithCampus(CampusQueryBuilder campusQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("campus", alias, campusQueryBuilder, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptCampus() => ExceptField("campus");

        public UndervisningsaktivitetQueryBuilder WithSkalEksporteresTilTimeplansystem(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("skalEksporteresTilTimeplansystem", alias, [include, skip]);

        public UndervisningsaktivitetQueryBuilder ExceptSkalEksporteresTilTimeplansystem() => ExceptField("skalEksporteresTilTimeplansystem");

        public UndervisningsaktivitetQueryBuilder WithTimeplaner(UndervisningsaktivitetTimeplanerConnectionQueryBuilder undervisningsaktivitetTimeplanerConnectionQueryBuilder, QueryBuilderParameter<int?> first = null, QueryBuilderParameter<string> after = null, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            var args = new List<QueryBuilderArgumentInfo>();
            if (first != null)
                args.Add(new() { ArgumentName = "first", ArgumentValue = first} );

            if (after != null)
                args.Add(new() { ArgumentName = "after", ArgumentValue = after} );

            return WithObjectField("timeplaner", alias, undervisningsaktivitetTimeplanerConnectionQueryBuilder, [include, skip], args);
        }

        public UndervisningsaktivitetQueryBuilder ExceptTimeplaner() => ExceptField("timeplaner");
    }
}
