// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class UndervisningsaktivitetsonskeLegacyIdInput : IGraphQlInputObject
    {
        private InputPropertyInfo _institusjonsnummer;
        private InputPropertyInfo _emnekode;
        private InputPropertyInfo _emneversjonskode;
        private InputPropertyInfo _terminkode;
        private InputPropertyInfo _arstall;
        private InputPropertyInfo _terminnummer;
        private InputPropertyInfo _aktivitetskode;
        private InputPropertyInfo _personlopenummer;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("institusjonsnummer")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("institusjonsnummer")]
        public QueryBuilderParameter<string> Institusjonsnummer
        {
            get => (QueryBuilderParameter<string>)_institusjonsnummer.Value;
            set => _institusjonsnummer = new() { Name = "institusjonsnummer", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emnekode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emnekode")]
        public QueryBuilderParameter<string> Emnekode
        {
            get => (QueryBuilderParameter<string>)_emnekode.Value;
            set => _emnekode = new() { Name = "emnekode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emneversjonskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emneversjonskode")]
        public QueryBuilderParameter<string> Emneversjonskode
        {
            get => (QueryBuilderParameter<string>)_emneversjonskode.Value;
            set => _emneversjonskode = new() { Name = "emneversjonskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminkode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminkode")]
        public QueryBuilderParameter<string> Terminkode
        {
            get => (QueryBuilderParameter<string>)_terminkode.Value;
            set => _terminkode = new() { Name = "terminkode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("arstall")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("arstall")]
        public QueryBuilderParameter<int?> Arstall
        {
            get => (QueryBuilderParameter<int?>)_arstall.Value;
            set => _arstall = new() { Name = "arstall", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminnummer")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<int?>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminnummer")]
        public QueryBuilderParameter<int?> Terminnummer
        {
            get => (QueryBuilderParameter<int?>)_terminnummer.Value;
            set => _terminnummer = new() { Name = "terminnummer", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("aktivitetskode")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("aktivitetskode")]
        public QueryBuilderParameter<string> Aktivitetskode
        {
            get => (QueryBuilderParameter<string>)_aktivitetskode.Value;
            set => _aktivitetskode = new() { Name = "aktivitetskode", Value = value };
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("personlopenummer")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("personlopenummer")]
        public QueryBuilderParameter<string> Personlopenummer
        {
            get => (QueryBuilderParameter<string>)_personlopenummer.Value;
            set => _personlopenummer = new() { Name = "personlopenummer", Value = value };
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_institusjonsnummer.Name != null) yield return _institusjonsnummer;
            if (_emnekode.Name != null) yield return _emnekode;
            if (_emneversjonskode.Name != null) yield return _emneversjonskode;
            if (_terminkode.Name != null) yield return _terminkode;
            if (_arstall.Name != null) yield return _arstall;
            if (_terminnummer.Name != null) yield return _terminnummer;
            if (_aktivitetskode.Name != null) yield return _aktivitetskode;
            if (_personlopenummer.Name != null) yield return _personlopenummer;
        }
    }
}
