// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class UndervisningsenhetSprakSlettetQueryBuilder : GraphQlQueryBuilder<UndervisningsenhetSprakSlettetQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "hendelsestype" },
            new() { Name = "tidspunkt" },
            new() { Name = "emne", IsComplex = true, QueryBuilderType = typeof(EmneQueryBuilder) },
            new() { Name = "undervisningsenhet", IsComplex = true, QueryBuilderType = typeof(UndervisningsenhetQueryBuilder) }
        };

        protected override string TypeName => "UndervisningsenhetSprakSlettet";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public UndervisningsenhetSprakSlettetQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public UndervisningsenhetSprakSlettetQueryBuilder ExceptId() => ExceptField("id");

        public UndervisningsenhetSprakSlettetQueryBuilder WithHendelsestype(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("hendelsestype", alias, [include, skip]);

        public UndervisningsenhetSprakSlettetQueryBuilder ExceptHendelsestype() => ExceptField("hendelsestype");

        public UndervisningsenhetSprakSlettetQueryBuilder WithTidspunkt(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("tidspunkt", alias, [include, skip]);

        public UndervisningsenhetSprakSlettetQueryBuilder ExceptTidspunkt() => ExceptField("tidspunkt");

        public UndervisningsenhetSprakSlettetQueryBuilder WithEmne(EmneQueryBuilder emneQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("emne", alias, emneQueryBuilder, [include, skip]);

        public UndervisningsenhetSprakSlettetQueryBuilder ExceptEmne() => ExceptField("emne");

        public UndervisningsenhetSprakSlettetQueryBuilder WithUndervisningsenhet(UndervisningsenhetQueryBuilder undervisningsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("undervisningsenhet", alias, undervisningsenhetQueryBuilder, [include, skip]);

        public UndervisningsenhetSprakSlettetQueryBuilder ExceptUndervisningsenhet() => ExceptField("undervisningsenhet");
    }
}
