// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class UndervisningstilpasningQueryBuilder : GraphQlQueryBuilder<UndervisningstilpasningQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "emne", IsComplex = true, QueryBuilderType = typeof(EmneQueryBuilder) },
            new() { Name = "tilpasningsperiode", IsComplex = true, QueryBuilderType = typeof(UndervisningstilpasningsperiodeQueryBuilder) },
            new() { Name = "kategori", IsComplex = true, QueryBuilderType = typeof(UndervisningstilpasningskategoriQueryBuilder) },
            new() { Name = "merknad", IsComplex = true, QueryBuilderType = typeof(UndervisningstilpasningsmerknadQueryBuilder) }
        };

        protected override string TypeName => "Undervisningstilpasning";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public UndervisningstilpasningQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public UndervisningstilpasningQueryBuilder ExceptId() => ExceptField("id");

        public UndervisningstilpasningQueryBuilder WithEmne(EmneQueryBuilder emneQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("emne", alias, emneQueryBuilder, [include, skip]);

        public UndervisningstilpasningQueryBuilder ExceptEmne() => ExceptField("emne");

        public UndervisningstilpasningQueryBuilder WithTilpasningsperiode(UndervisningstilpasningsperiodeQueryBuilder undervisningstilpasningsperiodeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("tilpasningsperiode", alias, undervisningstilpasningsperiodeQueryBuilder, [include, skip]);

        public UndervisningstilpasningQueryBuilder ExceptTilpasningsperiode() => ExceptField("tilpasningsperiode");

        public UndervisningstilpasningQueryBuilder WithKategori(UndervisningstilpasningskategoriQueryBuilder undervisningstilpasningskategoriQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("kategori", alias, undervisningstilpasningskategoriQueryBuilder, [include, skip]);

        public UndervisningstilpasningQueryBuilder ExceptKategori() => ExceptField("kategori");

        public UndervisningstilpasningQueryBuilder WithMerknad(UndervisningstilpasningsmerknadQueryBuilder undervisningstilpasningsmerknadQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("merknad", alias, undervisningstilpasningsmerknadQueryBuilder, [include, skip]);

        public UndervisningstilpasningQueryBuilder ExceptMerknad() => ExceptField("merknad");
    }
}
