// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Undervisningsenhet")]
    public partial class Undervisningsenhet : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("termin")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("termin")]
        public Termin Termin { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("terminnummer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("terminnummer")]
        public int? Terminnummer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("emne")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("emne")]
        public Emne Emne { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningsaktiviteter")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningsaktiviteter")]
        public UndervisningsenhetUndervisningsaktiviteterConnection Undervisningsaktiviteter { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("skalEksporteresTilLms")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("skalEksporteresTilLms")]
        public bool? SkalEksporteresTilLms { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("lmsRomkode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("lmsRomkode")]
        public string LmsRomkode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningenFolger")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningenFolger")]
        public Emne UndervisningenFolger { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("undervisningenFolgesAv")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("undervisningenFolgesAv")]
        public UndervisningsenhetUndervisningenFolgesAvConnection UndervisningenFolgesAv { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sprakvalg")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("sprakvalg")]
        public ICollection<UndervisningsenhetSprakvalg> Sprakvalg { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("startForEnkeltemneopptak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("startForEnkeltemneopptak")]
        public object StartForEnkeltemneopptak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("campuser")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("campuser")]
        public ICollection<Campus> Campuser { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studieretter")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studieretter")]
        public UndervisningsenhetStudieretterConnection Studieretter { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("soknader")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("soknader")]
        public UndervisningsenhetSoknaderConnection Soknader { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("personroller")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("personroller")]
        public UndervisningsenhetPersonrollerConnection Personroller { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("oppmeldingsperiode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("oppmeldingsperiode")]
        public UndervisningsOppmeldingsperiode Oppmeldingsperiode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("erLukket")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("erLukket")]
        public bool? ErLukket { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("skalEksporteresTilTimeplansystem")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("skalEksporteresTilTimeplansystem")]
        public bool? SkalEksporteresTilTimeplansystem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("studentKanVelgeCampus")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("studentKanVelgeCampus")]
        public bool? StudentKanVelgeCampus { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("opptaksgrupper")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("opptaksgrupper")]
        public ICollection<OpptaksgruppeForUndervisningsenhet> Opptaksgrupper { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("oppmote")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("oppmote")]
        public ICollection<OppmoteTilUndervisning> Oppmote { get; set; }
    }
}
