// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class UtdanningsplanEksternresultaterConnectionEdgeQueryBuilder : GraphQlQueryBuilder<UtdanningsplanEksternresultaterConnectionEdgeQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "cursor" },
            new() { Name = "node", IsComplex = true, QueryBuilderType = typeof(EksternresultatIUtdanningsplanQueryBuilder) }
        };

        protected override string TypeName => "UtdanningsplanEksternresultaterConnectionEdge";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public UtdanningsplanEksternresultaterConnectionEdgeQueryBuilder WithCursor(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("cursor", alias, [include, skip]);

        public UtdanningsplanEksternresultaterConnectionEdgeQueryBuilder ExceptCursor() => ExceptField("cursor");

        public UtdanningsplanEksternresultaterConnectionEdgeQueryBuilder WithNode(EksternresultatIUtdanningsplanQueryBuilder eksternresultatIUtdanningsplanQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("node", alias, eksternresultatIUtdanningsplanQueryBuilder, [include, skip]);

        public UtdanningsplanEksternresultaterConnectionEdgeQueryBuilder ExceptNode() => ExceptField("node");
    }
}
