// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    [GraphQlObjectType("Utdanningsplanelement")]
    public partial class Utdanningsplanelement : INode
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("id")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("kode")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("kode")]
        public string Kode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("navnAlleSprak")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("navnAlleSprak")]
        public UtdanningsplanelementnavnAlleSprak NavnAlleSprak { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utdanningsplanelementtype")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("utdanningsplanelementtype")]
        public Utdanningsplanelementtype Utdanningsplanelementtype { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("fordelStudiepoengPaTerminer")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("fordelStudiepoengPaTerminer")]
        public bool? FordelStudiepoengPaTerminer { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("vekting")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("vekting")]
        public Utdanningsplanelementtypevekting Vekting { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("urler")]
        #endif
        [System.Text.Json.Serialization.JsonPropertyName("urler")]
        public UtdanningsplanelementUrler Urler { get; set; }
    }
}
