// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class VurderingsoppbygningsdelIHierarkiQueryBuilder : GraphQlQueryBuilder<VurderingsoppbygningsdelIHierarkiQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "id" },
            new() { Name = "hierarkiskInformasjon", IsComplex = true, QueryBuilderType = typeof(VurderingsoppbygningsdelHierarkiskInformasjonQueryBuilder) },
            new() { Name = "vurderingsoppbygningsdel", IsComplex = true, QueryBuilderType = typeof(VurderingsoppbygningsdelQueryBuilder) },
            new() { Name = "parent", IsComplex = true, QueryBuilderType = typeof(VurderingsoppbygningsdelIHierarkiQueryBuilder) },
            new() { Name = "children", IsComplex = true, QueryBuilderType = typeof(VurderingsoppbygningsdelIHierarkiQueryBuilder) }
        };

        protected override string TypeName => "VurderingsoppbygningsdelIHierarki";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public VurderingsoppbygningsdelIHierarkiQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("id", alias, [include, skip]);

        public VurderingsoppbygningsdelIHierarkiQueryBuilder ExceptId() => ExceptField("id");

        public VurderingsoppbygningsdelIHierarkiQueryBuilder WithHierarkiskInformasjon(VurderingsoppbygningsdelHierarkiskInformasjonQueryBuilder vurderingsoppbygningsdelHierarkiskInformasjonQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("hierarkiskInformasjon", alias, vurderingsoppbygningsdelHierarkiskInformasjonQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelIHierarkiQueryBuilder ExceptHierarkiskInformasjon() => ExceptField("hierarkiskInformasjon");

        public VurderingsoppbygningsdelIHierarkiQueryBuilder WithVurderingsoppbygningsdel(VurderingsoppbygningsdelQueryBuilder vurderingsoppbygningsdelQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("vurderingsoppbygningsdel", alias, vurderingsoppbygningsdelQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelIHierarkiQueryBuilder ExceptVurderingsoppbygningsdel() => ExceptField("vurderingsoppbygningsdel");

        public VurderingsoppbygningsdelIHierarkiQueryBuilder WithParent(VurderingsoppbygningsdelIHierarkiQueryBuilder vurderingsoppbygningsdelIHierarkiQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("parent", alias, vurderingsoppbygningsdelIHierarkiQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelIHierarkiQueryBuilder ExceptParent() => ExceptField("parent");

        public VurderingsoppbygningsdelIHierarkiQueryBuilder WithChildren(VurderingsoppbygningsdelIHierarkiQueryBuilder vurderingsoppbygningsdelIHierarkiQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("children", alias, vurderingsoppbygningsdelIHierarkiQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelIHierarkiQueryBuilder ExceptChildren() => ExceptField("children");
    }
}
