// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder : GraphQlQueryBuilder<VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "en" },
            new() { Name = "nb" },
            new() { Name = "nn" },
            new() { Name = "se" }
        };

        protected override string TypeName => "VurderingsoppbygningsdelsnavnAlleSprak";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder WithEn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("en", alias, [include, skip]);

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder ExceptEn() => ExceptField("en");

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder WithNb(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("nb", alias, [include, skip]);

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder ExceptNb() => ExceptField("nb");

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder WithNn(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("nn", alias, [include, skip]);

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder ExceptNn() => ExceptField("nn");

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder WithSe(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("se", alias, [include, skip]);

        public VurderingsoppbygningsdelsnavnAlleSprakQueryBuilder ExceptSe() => ExceptField("se");
    }
}
