// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace FS.SDK.GraphQL.Model
{
    public partial class VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder : GraphQlQueryBuilder<VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
        {
            new() { Name = "edges", IsComplex = true, QueryBuilderType = typeof(VurderingsoppbygningsdelVurderingsenheterConnectionEdgeQueryBuilder) },
            new() { Name = "pageInfo", IsComplex = true, QueryBuilderType = typeof(PageInfoQueryBuilder) },
            new() { Name = "nodes", IsComplex = true, QueryBuilderType = typeof(VurderingsenhetQueryBuilder) },
            new() { Name = "totalCount" }
        };

        protected override string TypeName => "VurderingsoppbygningsdelVurderingsenheterConnection";

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields => AllFieldMetadata;

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder WithEdges(VurderingsoppbygningsdelVurderingsenheterConnectionEdgeQueryBuilder vurderingsoppbygningsdelVurderingsenheterConnectionEdgeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("edges", alias, vurderingsoppbygningsdelVurderingsenheterConnectionEdgeQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder ExceptEdges() => ExceptField("edges");

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder WithPageInfo(PageInfoQueryBuilder pageInfoQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("pageInfo", alias, pageInfoQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder ExceptPageInfo() => ExceptField("pageInfo");

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder WithNodes(VurderingsenhetQueryBuilder vurderingsenhetQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithObjectField("nodes", alias, vurderingsenhetQueryBuilder, [include, skip]);

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder ExceptNodes() => ExceptField("nodes");

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder WithTotalCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null) => WithScalarField("totalCount", alias, [include, skip]);

        public VurderingsoppbygningsdelVurderingsenheterConnectionQueryBuilder ExceptTotalCount() => ExceptField("totalCount");
    }
}
